# SPDX-FileCopyrightText: 2024 Cezar M. Tigaret <cezar.tigaret@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LGPL-2.1-or-later

[project]
name = "scipyen"
# version = "0.0.1"
# dependencies = ["pygments"]
readme = "README.md"
authors = [{name="Cezar M. Tigaret", email="cezar.tigaret@gmail.com"}]
description = "Scientific python environment for neuroscience"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers, End-users",
    "Topic :: Data Analysis :: Software Development"
    ]
license = {file = "GPL-3.0-or-later"}
dynamic = ["version"]

# license-files = ["LICENSES/*"]
keywords = ["neuroscience", "electrophysiology", "patch-clamp", "two-photon"]

[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/ctigaret/scipyen"
Issues = "https://github.com/ctigaret/scipyen/issues"

[tool.setuptools_scm]
#version_file = "scipyen/_version.py"
