#! /bin/sh 

realscript=`realpath $0`
scipyendir=`dirname $realscript`
scipyenvdir=`dirname $scipyendir`

if [ -z $VIRTUAL_ENV ]; then
    source $scipyenvdir/bin/activate
fi

if [ -z $BROWSER ]; then
    if [ -a $scipyenvdir/bin/browser ]; then
        source $scipyenvdir/bin/browser
    fi
fi

# NOTE: 2021-02-04 18:00:07
# On linux, prevent KDE or other DEs theming from overriding the resources 
# (colors etc) in the InterViews GUI
xrdb -merge $scipyendir/neuron_python/app-defaults/nrniv

python3 $scipyendir/scipyen.py &
