#! /bin/sh 
realscript=`realpath $0`
scipyendir=`dirname $realscript`
source $HOME/.scipyenrc # supplies the shell function scipyact created by make_

if [ -z $VIRTUAL_ENV ]; then
    scipyact
fi

echo "Using Python environment in ${VIRTUAL_ENV}"
echo ""
# echo "PYTHONHOME=$PYTHONHOME"
# echo "PYTHONPATH=$PYTHONPATH"
# echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH"

if [ -z $BROWSER ]; then
    if [ -a $VIRTUAL_ENV/bin/browser ]; then
        source $VIRTUAL_ENV/bin/browser
    fi
fi

# export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib:$VIRTUAL_ENV/lib64:$LD_LIBRARY_PATH

# NOTE: 2021-02-04 18:00:07
# On linux, override KDE or other DEs theming from overriding the resources 
# (colors etc) in the InterViews GUI
a=`which xrdb` # do we have xrdb to read the X11 resources? (on Unix almost surely yes)
if [ $0 == 0 ] ; then
    if [ -r $scipyendir/neuron_python/app-defaults/nrniv ] ; then
        xrdb -merge $scipyendir/neuron_python/app-defaults/nrniv
    fi
fi

python3 $scipyendir/scipyen.py
