from gui.resources import breeze-dark_16x16_rc.py
from gui.resources import breeze-dark_22x22_rc.py
from gui.resources import breeze-dark_8x8_rc.py
from gui.resources import breeze-dark_actions_rc.py
from gui.resources import breeze-dark_animations_rc.py
from gui.resources import breeze-dark_applets_rc.py
from gui.resources import breeze-dark_apps_rc.py
from gui.resources import breeze-dark_categories_rc.py
from gui.resources import breeze-dark_devices_rc.py
from gui.resources import breeze-dark_emblems_rc.py
from gui.resources import breeze-dark_emotes_rc.py
from gui.resources import breeze-dark_mimetypes_rc.py
from gui.resources import breeze-dark_places_rc.py
from gui.resources import breeze-dark_preferences_rc.py
from gui.resources import breeze-dark_status_rc.py
from gui.resources import breeze_16x16_rc.py
from gui.resources import breeze_22x22_rc.py
from gui.resources import breeze_actions_rc.py
from gui.resources import breeze_animations_rc.py
from gui.resources import breeze_applets_rc.py
from gui.resources import breeze_apps_rc.py
from gui.resources import breeze_categories_rc.py
from gui.resources import breeze_devices_rc.py
from gui.resources import breeze_emblems_rc.py
from gui.resources import breeze_emotes_rc.py
from gui.resources import breeze_mimetypes_rc.py
from gui.resources import breeze_places_rc.py
from gui.resources import breeze_preferences_rc.py
from gui.resources import breeze_status_rc.py
