# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'imageviewer.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QLabel,
    QLayout, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QSlider, QSpinBox, QStatusBar,
    QVBoxLayout, QWidget)

class Ui_ImageViewerWindow(object):
    def setupUi(self, ImageViewerWindow):
        if not ImageViewerWindow.objectName():
            ImageViewerWindow.setObjectName(u"ImageViewerWindow")
        ImageViewerWindow.resize(525, 541)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ImageViewerWindow.sizePolicy().hasHeightForWidth())
        ImageViewerWindow.setSizePolicy(sizePolicy)
        self.actionClose = QAction(ImageViewerWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionColorMap = QAction(ImageViewerWindow)
        self.actionColorMap.setObjectName(u"actionColorMap")
        self.actionImageScale = QAction(ImageViewerWindow)
        self.actionImageScale.setObjectName(u"actionImageScale")
        self.actionImageGamma = QAction(ImageViewerWindow)
        self.actionImageGamma.setObjectName(u"actionImageGamma")
        self.actionOpen = QAction(ImageViewerWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionCrosshair_Cursor = QAction(ImageViewerWindow)
        self.actionCrosshair_Cursor.setObjectName(u"actionCrosshair_Cursor")
        self.actionVertical_Cursor = QAction(ImageViewerWindow)
        self.actionVertical_Cursor.setObjectName(u"actionVertical_Cursor")
        self.actionHorizontal_Cursor = QAction(ImageViewerWindow)
        self.actionHorizontal_Cursor.setObjectName(u"actionHorizontal_Cursor")
        self.actionRemove_Cursor = QAction(ImageViewerWindow)
        self.actionRemove_Cursor.setObjectName(u"actionRemove_Cursor")
        self.actionExportSceneAsFile = QAction(ImageViewerWindow)
        self.actionExportSceneAsFile.setObjectName(u"actionExportSceneAsFile")
        icon = QIcon(QIcon.fromTheme(u"document-save"))
        self.actionExportSceneAsFile.setIcon(icon)
        self.actionExportAsSVG = QAction(ImageViewerWindow)
        self.actionExportAsSVG.setObjectName(u"actionExportAsSVG")
        self.actionExportAsTIFF = QAction(ImageViewerWindow)
        self.actionExportAsTIFF.setObjectName(u"actionExportAsTIFF")
        self.actionSaveToFile = QAction(ImageViewerWindow)
        self.actionSaveToFile.setObjectName(u"actionSaveToFile")
        self.actionSaveToFile.setIcon(icon)
        self.actionView = QAction(ImageViewerWindow)
        self.actionView.setObjectName(u"actionView")
        self.actionRefresh = QAction(ImageViewerWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        self.actionHDF5 = QAction(ImageViewerWindow)
        self.actionHDF5.setObjectName(u"actionHDF5")
        self.actionPickle = QAction(ImageViewerWindow)
        self.actionPickle.setObjectName(u"actionPickle")
        self.actionExportAsHDF5 = QAction(ImageViewerWindow)
        self.actionExportAsHDF5.setObjectName(u"actionExportAsHDF5")
        self.actionExportAsPickle = QAction(ImageViewerWindow)
        self.actionExportAsPickle.setObjectName(u"actionExportAsPickle")
        self.actionExportSceneToWorkspace = QAction(ImageViewerWindow)
        self.actionExportSceneToWorkspace.setObjectName(u"actionExportSceneToWorkspace")
        icon1 = QIcon(QIcon.fromTheme(u"document-export"))
        self.actionExportSceneToWorkspace.setIcon(icon1)
        self.actionExportToWorkspace = QAction(ImageViewerWindow)
        self.actionExportToWorkspace.setObjectName(u"actionExportToWorkspace")
        self.actionExportToWorkspace.setIcon(icon1)
        self.centralwidget = QWidget(ImageViewerWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.viewerWidgetContainer = QWidget(self.centralwidget)
        self.viewerWidgetContainer.setObjectName(u"viewerWidgetContainer")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.viewerWidgetContainer.sizePolicy().hasHeightForWidth())
        self.viewerWidgetContainer.setSizePolicy(sizePolicy1)

        self.verticalLayout.addWidget(self.viewerWidgetContainer)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.framesLabel = QLabel(self.centralwidget)
        self.framesLabel.setObjectName(u"framesLabel")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.framesLabel.sizePolicy().hasHeightForWidth())
        self.framesLabel.setSizePolicy(sizePolicy2)

        self.horizontalLayout.addWidget(self.framesLabel)

        self.framesQSpinBox = QSpinBox(self.centralwidget)
        self.framesQSpinBox.setObjectName(u"framesQSpinBox")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.framesQSpinBox.sizePolicy().hasHeightForWidth())
        self.framesQSpinBox.setSizePolicy(sizePolicy3)
        self.framesQSpinBox.setMinimumSize(QSize(48, 0))
        self.framesQSpinBox.setMouseTracking(True)
        self.framesQSpinBox.setProperty(u"showGroupSeparator", True)
        self.framesQSpinBox.setMaximum(999999999)

        self.horizontalLayout.addWidget(self.framesQSpinBox)

        self.nFramesLabel = QLabel(self.centralwidget)
        self.nFramesLabel.setObjectName(u"nFramesLabel")

        self.horizontalLayout.addWidget(self.nFramesLabel)

        self.framesQSlider = QSlider(self.centralwidget)
        self.framesQSlider.setObjectName(u"framesQSlider")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.framesQSlider.sizePolicy().hasHeightForWidth())
        self.framesQSlider.setSizePolicy(sizePolicy4)
        self.framesQSlider.setMouseTracking(True)
        self.framesQSlider.setAutoFillBackground(False)
        self.framesQSlider.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout.addWidget(self.framesQSlider)


        self.verticalLayout.addLayout(self.horizontalLayout)


        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        ImageViewerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(ImageViewerWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 525, 28))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuExport = QMenu(self.menuFile)
        self.menuExport.setObjectName(u"menuExport")
        self.menuSave = QMenu(self.menuFile)
        self.menuSave.setObjectName(u"menuSave")
        ImageViewerWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(ImageViewerWindow)
        self.statusbar.setObjectName(u"statusbar")
        ImageViewerWindow.setStatusBar(self.statusbar)
#if QT_CONFIG(shortcut)
        self.framesLabel.setBuddy(self.framesQSpinBox)
#endif // QT_CONFIG(shortcut)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionView)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRefresh)
        self.menuExport.addAction(self.actionExportSceneAsFile)
        self.menuExport.addAction(self.actionExportSceneToWorkspace)
        self.menuSave.addAction(self.actionSaveToFile)
        self.menuSave.addAction(self.actionExportToWorkspace)

        self.retranslateUi(ImageViewerWindow)
        self.actionClose.triggered.connect(ImageViewerWindow.close)

        QMetaObject.connectSlotsByName(ImageViewerWindow)
    # setupUi

    def retranslateUi(self, ImageViewerWindow):
        ImageViewerWindow.setWindowTitle(QCoreApplication.translate("ImageViewerWindow", u"Image Viewer", None))
        self.actionClose.setText(QCoreApplication.translate("ImageViewerWindow", u"&Close", None))
        self.actionColorMap.setText(QCoreApplication.translate("ImageViewerWindow", u"&Color Map", None))
        self.actionImageScale.setText(QCoreApplication.translate("ImageViewerWindow", u"&Image Scale", None))
        self.actionImageGamma.setText(QCoreApplication.translate("ImageViewerWindow", u"Image &Gamma", None))
        self.actionOpen.setText(QCoreApplication.translate("ImageViewerWindow", u"&Open", None))
        self.actionCrosshair_Cursor.setText(QCoreApplication.translate("ImageViewerWindow", u"Crosshair", None))
        self.actionVertical_Cursor.setText(QCoreApplication.translate("ImageViewerWindow", u"Vertical", None))
        self.actionHorizontal_Cursor.setText(QCoreApplication.translate("ImageViewerWindow", u"Horizontal", None))
        self.actionRemove_Cursor.setText(QCoreApplication.translate("ImageViewerWindow", u"Remove Cursor...", None))
        self.actionExportSceneAsFile.setText(QCoreApplication.translate("ImageViewerWindow", u"To File", None))
        self.actionExportAsSVG.setText(QCoreApplication.translate("ImageViewerWindow", u"&SVG", None))
        self.actionExportAsTIFF.setText(QCoreApplication.translate("ImageViewerWindow", u"&TIFF", None))
        self.actionSaveToFile.setText(QCoreApplication.translate("ImageViewerWindow", u"To File", None))
        self.actionView.setText(QCoreApplication.translate("ImageViewerWindow", u"&View...", None))
#if QT_CONFIG(tooltip)
        self.actionView.setToolTip(QCoreApplication.translate("ImageViewerWindow", u"View image from workspace", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionView.setStatusTip(QCoreApplication.translate("ImageViewerWindow", u"View image from workspace", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionView.setWhatsThis(QCoreApplication.translate("ImageViewerWindow", u"View image from workspace", None))
#endif // QT_CONFIG(whatsthis)
        self.actionRefresh.setText(QCoreApplication.translate("ImageViewerWindow", u"&Refresh", None))
#if QT_CONFIG(tooltip)
        self.actionRefresh.setToolTip(QCoreApplication.translate("ImageViewerWindow", u"Refresh image display - only works for images in the workspace", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionRefresh.setStatusTip(QCoreApplication.translate("ImageViewerWindow", u"Refresh image display - only works for images in the workspace", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionRefresh.setWhatsThis(QCoreApplication.translate("ImageViewerWindow", u"Refresh image display - only works for images in the workspace", None))
#endif // QT_CONFIG(whatsthis)
        self.actionHDF5.setText(QCoreApplication.translate("ImageViewerWindow", u"HDF5", None))
        self.actionPickle.setText(QCoreApplication.translate("ImageViewerWindow", u"Pickle", None))
        self.actionExportAsHDF5.setText(QCoreApplication.translate("ImageViewerWindow", u"HDF5", None))
        self.actionExportAsPickle.setText(QCoreApplication.translate("ImageViewerWindow", u"Pickle", None))
        self.actionExportSceneToWorkspace.setText(QCoreApplication.translate("ImageViewerWindow", u"To workspace", None))
        self.actionExportToWorkspace.setText(QCoreApplication.translate("ImageViewerWindow", u"To workspace", None))
        self.framesLabel.setText(QCoreApplication.translate("ImageViewerWindow", u"Frame:", None))
#if QT_CONFIG(tooltip)
        self.framesQSpinBox.setToolTip(QCoreApplication.translate("ImageViewerWindow", u"Select frame", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.framesQSpinBox.setWhatsThis(QCoreApplication.translate("ImageViewerWindow", u"Current frame number", None))
#endif // QT_CONFIG(whatsthis)
        self.nFramesLabel.setText(QCoreApplication.translate("ImageViewerWindow", u"of: 0", None))
#if QT_CONFIG(tooltip)
        self.framesQSlider.setToolTip(QCoreApplication.translate("ImageViewerWindow", u"Select frame", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.framesQSlider.setWhatsThis(QCoreApplication.translate("ImageViewerWindow", u"Frame selector slider", None))
#endif // QT_CONFIG(whatsthis)
        self.menuFile.setTitle(QCoreApplication.translate("ImageViewerWindow", u"Fi&le", None))
        self.menuExport.setTitle(QCoreApplication.translate("ImageViewerWindow", u"&Export frame", None))
        self.menuSave.setTitle(QCoreApplication.translate("ImageViewerWindow", u"&Save", None))
    # retranslateUi

