# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QColumnView,
    QComboBox, QDockWidget, QFrame, QGridLayout,
    QHBoxLayout, QHeaderView, QLabel, QLayout,
    QListView, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QSpacerItem, QStackedWidget, QStatusBar,
    QTabWidget, QTableView, QToolBar, QToolButton,
    QTreeView, QTreeWidget, QTreeWidgetItem, QVBoxLayout,
    QWidget)

from iolib.navigation.navigator import UrlNavigator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(898, 843)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(True)
        icon = QIcon(QIcon.fromTheme(u"python"))
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QTabWidget.TabShape.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon1 = QIcon(QIcon.fromTheme(u"document-save"))
        self.actionSave.setIcon(icon1)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon2 = QIcon(QIcon.fromTheme(u"application-exit"))
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setMenuRole(QAction.MenuRole.QuitRole)
        self.action_Console = QAction(MainWindow)
        self.action_Console.setObjectName(u"action_Console")
        icon3 = QIcon(QIcon.fromTheme(u"scriptnew"))
        self.action_Console.setIcon(icon3)
        self.actionRestore_Workspace = QAction(MainWindow)
        self.actionRestore_Workspace.setObjectName(u"actionRestore_Workspace")
        self.actionHelp_On_Console = QAction(MainWindow)
        self.actionHelp_On_Console.setObjectName(u"actionHelp_On_Console")
        icon4 = QIcon(QIcon.fromTheme(u"help-contextual"))
        self.actionHelp_On_Console.setIcon(icon4)
        self.actionHelp_On_Console.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.actionImport_PrairieView_data = QAction(MainWindow)
        self.actionImport_PrairieView_data.setObjectName(u"actionImport_PrairieView_data")
        icon5 = QIcon(QIcon.fromTheme(u"document-import"))
        self.actionImport_PrairieView_data.setIcon(icon5)
        self.actionImport_XY_Raster_Scan_File = QAction(MainWindow)
        self.actionImport_XY_Raster_Scan_File.setObjectName(u"actionImport_XY_Raster_Scan_File")
        icon6 = QIcon(QIcon.fromTheme(u"document-open"))
        self.actionImport_XY_Raster_Scan_File.setIcon(icon6)
        self.actionImport_Protocol_File = QAction(MainWindow)
        self.actionImport_Protocol_File.setObjectName(u"actionImport_Protocol_File")
        self.actionOpen_Image_File = QAction(MainWindow)
        self.actionOpen_Image_File.setObjectName(u"actionOpen_Image_File")
        self.actionOpen_Scan_Data_File = QAction(MainWindow)
        self.actionOpen_Scan_Data_File.setObjectName(u"actionOpen_Scan_Data_File")
        self.actionView_Data_New_Window = QAction(MainWindow)
        self.actionView_Data_New_Window.setObjectName(u"actionView_Data_New_Window")
        icon7 = QIcon(QIcon.fromTheme(u"window-new"))
        self.actionView_Data_New_Window.setIcon(icon7)
        self.actionView_Data = QAction(MainWindow)
        self.actionView_Data.setObjectName(u"actionView_Data")
        icon8 = QIcon(QIcon.fromTheme(u"fileview-preview-symbolic"))
        self.actionView_Data.setIcon(icon8)
        self.actionReload_Plugins = QAction(MainWindow)
        self.actionReload_Plugins.setObjectName(u"actionReload_Plugins")
        icon9 = QIcon(QIcon.fromTheme(u"plugins"))
        self.actionReload_Plugins.setIcon(icon9)
        self.actionOpen_Image_File_Using_BioFormats = QAction(MainWindow)
        self.actionOpen_Image_File_Using_BioFormats.setObjectName(u"actionOpen_Image_File_Using_BioFormats")
        self.actionChange_Working_Directory = QAction(MainWindow)
        self.actionChange_Working_Directory.setObjectName(u"actionChange_Working_Directory")
        icon10 = QIcon(QIcon.fromTheme(u"document-open-folder"))
        self.actionChange_Working_Directory.setIcon(icon10)
        self.actionNew_Signal_Viewer = QAction(MainWindow)
        self.actionNew_Signal_Viewer.setObjectName(u"actionNew_Signal_Viewer")
        self.actionNew_Image_Viewer = QAction(MainWindow)
        self.actionNew_Image_Viewer.setObjectName(u"actionNew_Image_Viewer")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionOpen.setIcon(icon6)
        self.actionOpen_Files = QAction(MainWindow)
        self.actionOpen_Files.setObjectName(u"actionOpen_Files")
        self.actionSave_pickle = QAction(MainWindow)
        self.actionSave_pickle.setObjectName(u"actionSave_pickle")
        self.actionScriptRun = QAction(MainWindow)
        self.actionScriptRun.setObjectName(u"actionScriptRun")
        self.actionScriptToConsole = QAction(MainWindow)
        self.actionScriptToConsole.setObjectName(u"actionScriptToConsole")
        self.actionConsole_font = QAction(MainWindow)
        self.actionConsole_font.setObjectName(u"actionConsole_font")
        self.actionConsole_font.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionEditor = QAction(MainWindow)
        self.actionEditor.setObjectName(u"actionEditor")
        self.actionNewViewer = QAction(MainWindow)
        self.actionNewViewer.setObjectName(u"actionNewViewer")
        self.actionExternal_IPython = QAction(MainWindow)
        self.actionExternal_IPython.setObjectName(u"actionExternal_IPython")
        self.actionConsole = QAction(MainWindow)
        self.actionConsole.setObjectName(u"actionConsole")
        self.actionExternalIPython = QAction(MainWindow)
        self.actionExternalIPython.setObjectName(u"actionExternalIPython")
        self.actionExternalNrnIPython = QAction(MainWindow)
        self.actionExternalNrnIPython.setObjectName(u"actionExternalNrnIPython")
        self.actionConsole_Client_for_Neuron = QAction(MainWindow)
        self.actionConsole_Client_for_Neuron.setObjectName(u"actionConsole_Client_for_Neuron")
        self.actionRunning_IPython = QAction(MainWindow)
        self.actionRunning_IPython.setObjectName(u"actionRunning_IPython")
        self.actionRunning_IPython_for_Neuron = QAction(MainWindow)
        self.actionRunning_IPython_for_Neuron.setObjectName(u"actionRunning_IPython_for_Neuron")
        self.actionGUI_Style = QAction(MainWindow)
        self.actionGUI_Style.setObjectName(u"actionGUI_Style")
        icon11 = QIcon(QIcon.fromTheme(u"edit-paste-style"))
        self.actionGUI_Style.setIcon(icon11)
        self.actionGUI_Style.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionAuto_launch_Script_Manager = QAction(MainWindow)
        self.actionAuto_launch_Script_Manager.setObjectName(u"actionAuto_launch_Script_Manager")
        self.actionAuto_launch_Script_Manager.setCheckable(True)
        icon12 = QIcon(QIcon.fromTheme(u"dialog-scripts"))
        self.actionAuto_launch_Script_Manager.setIcon(icon12)
        self.actionAuto_launch_Script_Manager.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionChoose_code_editor = QAction(MainWindow)
        self.actionChoose_code_editor.setObjectName(u"actionChoose_code_editor")
        icon13 = QIcon(QIcon.fromTheme(u"editor"))
        self.actionChoose_code_editor.setIcon(icon13)
        self.actionChoose_code_editor.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionUse_system_s_default_code_editor = QAction(MainWindow)
        self.actionUse_system_s_default_code_editor.setObjectName(u"actionUse_system_s_default_code_editor")
        self.actionUse_system_s_default_code_editor.setCheckable(True)
        self.actionUse_system_s_default_code_editor.setIcon(icon13)
        self.actionAuto_delete_viewer = QAction(MainWindow)
        self.actionAuto_delete_viewer.setObjectName(u"actionAuto_delete_viewer")
        self.actionAuto_delete_viewer.setCheckable(True)
        icon14 = QIcon(QIcon.fromTheme(u"window-unpin"))
        self.actionAuto_delete_viewer.setIcon(icon14)
        self.actionAuto_delete_viewer.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionOpen_System_Terminal = QAction(MainWindow)
        self.actionOpen_System_Terminal.setObjectName(u"actionOpen_System_Terminal")
        self.actionOpen_System_Terminal.setEnabled(True)
        self.actionOpen_System_Terminal.setIcon(icon3)
        self.actionOpen_System_Terminal.setVisible(True)
        self.actionSet_user_plugins_directory = QAction(MainWindow)
        self.actionSet_user_plugins_directory.setObjectName(u"actionSet_user_plugins_directory")
        icon15 = QIcon(QIcon.fromTheme(u"folder-extension-symbolic"))
        self.actionSet_user_plugins_directory.setIcon(icon15)
        self.actionImport_Electrophysiology_File = QAction(MainWindow)
        self.actionImport_Electrophysiology_File.setObjectName(u"actionImport_Electrophysiology_File")
        self.actionRecent = QAction(MainWindow)
        self.actionRecent.setObjectName(u"actionRecent")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        icon16 = QIcon(QIcon.fromTheme(u"help-about"))
        self.actionAbout.setIcon(icon16)
        self.actionAbout.setMenuRole(QAction.MenuRole.AboutRole)
        self.actionAbout_Components = QAction(MainWindow)
        self.actionAbout_Components.setObjectName(u"actionAbout_Components")
        icon17 = QIcon(QIcon.fromTheme(u"tools-symbolic"))
        self.actionAbout_Components.setIcon(icon17)
        self.actionAbout_Components.setMenuRole(QAction.MenuRole.ApplicationSpecificRole)
        self.actionLicense = QAction(MainWindow)
        self.actionLicense.setObjectName(u"actionLicense")
        icon18 = QIcon(QIcon.fromTheme(u"license"))
        self.actionLicense.setIcon(icon18)
        self.actionLicense.setMenuRole(QAction.MenuRole.AboutRole)
        self.actionAbout_Qt = QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        self.actionAbout_Qt.setIcon(icon16)
        self.actionAbout_Qt.setMenuRole(QAction.MenuRole.AboutQtRole)
        self.actionSet_Icon_Size = QAction(MainWindow)
        self.actionSet_Icon_Size.setObjectName(u"actionSet_Icon_Size")
        icon19 = QIcon(QIcon.fromTheme(u"image-resize-symbolic"))
        self.actionSet_Icon_Size.setIcon(icon19)
        self.actionSet_Icon_Size.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionConfigure_external_HDF_viewer = QAction(MainWindow)
        self.actionConfigure_external_HDF_viewer.setObjectName(u"actionConfigure_external_HDF_viewer")
        self.actionConfigure_external_HDF_viewer.setEnabled(False)
        self.actionConfigure_external_HDF_viewer.setVisible(False)
        self.actionConfigure_external_HDF_viewer.setIconVisibleInMenu(False)
        self.actionConfigure_external_HDF_viewer.setShortcutVisibleInContextMenu(False)
        self.actionUse_system_default_font = QAction(MainWindow)
        self.actionUse_system_default_font.setObjectName(u"actionUse_system_default_font")
        self.actionUse_system_default_font.setCheckable(True)
        self.actionUse_system_default_font.setChecked(True)
        self.actionWorkplaceFont = QAction(MainWindow)
        self.actionWorkplaceFont.setObjectName(u"actionWorkplaceFont")
        self.actionWorkplaceFont.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionCommandHistoryFont = QAction(MainWindow)
        self.actionCommandHistoryFont.setObjectName(u"actionCommandHistoryFont")
        self.actionCommandHistoryFont.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionDisplay_In_Console = QAction(MainWindow)
        self.actionDisplay_In_Console.setObjectName(u"actionDisplay_In_Console")
        icon20 = QIcon(QIcon.fromTheme(u"quickview-symbolic"))
        self.actionDisplay_In_Console.setIcon(icon20)
        self.actionWorkspaceIconSize = QAction(MainWindow)
        self.actionWorkspaceIconSize.setObjectName(u"actionWorkspaceIconSize")
        self.actionWorkspaceIconSize.setIcon(icon19)
        self.actionFile_SystemIconSize = QAction(MainWindow)
        self.actionFile_SystemIconSize.setObjectName(u"actionFile_SystemIconSize")
        self.actionFile_SystemIconSize.setIcon(icon19)
        self.actionUse_Native_Menu_Bar = QAction(MainWindow)
        self.actionUse_Native_Menu_Bar.setObjectName(u"actionUse_Native_Menu_Bar")
        self.actionUse_Native_Menu_Bar.setCheckable(True)
        icon21 = QIcon(QIcon.fromTheme(u"application-menu-symbolic"))
        self.actionUse_Native_Menu_Bar.setIcon(icon21)
        self.actionUse_New_Navigator_Look = QAction(MainWindow)
        self.actionUse_New_Navigator_Look.setObjectName(u"actionUse_New_Navigator_Look")
        self.actionUse_New_Navigator_Look.setCheckable(True)
        icon22 = QIcon(QIcon.fromTheme(u"color-fill"))
        self.actionUse_New_Navigator_Look.setIcon(icon22)
        self.actionUseShellAutomagic = QAction(MainWindow)
        self.actionUseShellAutomagic.setObjectName(u"actionUseShellAutomagic")
        self.actionUseShellAutomagic.setCheckable(True)
        icon23 = QIcon(QIcon.fromTheme(u"tools-wizard"))
        self.actionUseShellAutomagic.setIcon(icon23)
        self.actionUseShellAutomagic.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionHide_Filtered_out_File_Names = QAction(MainWindow)
        self.actionHide_Filtered_out_File_Names.setObjectName(u"actionHide_Filtered_out_File_Names")
        self.actionHide_Filtered_out_File_Names.setCheckable(True)
        icon24 = QIcon(QIcon.fromTheme(u"view-hidden"))
        self.actionHide_Filtered_out_File_Names.setIcon(icon24)
        self.actionHide_Filtered_out_File_Names.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionTool_Button_Style = QAction(MainWindow)
        self.actionTool_Button_Style.setObjectName(u"actionTool_Button_Style")
        self.actionTool_Button_Style.setIcon(icon11)
        self.actionTool_Button_Style.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.actionPython_help = QAction(MainWindow)
        self.actionPython_help.setObjectName(u"actionPython_help")
        self.actionPython_help.setIcon(icon4)
        self.actionOpeningARecentFileNavigatesToItsDirectory = QAction(MainWindow)
        self.actionOpeningARecentFileNavigatesToItsDirectory.setObjectName(u"actionOpeningARecentFileNavigatesToItsDirectory")
        self.actionOpeningARecentFileNavigatesToItsDirectory.setCheckable(True)
        icon25 = QIcon(QIcon.fromTheme(u"dirsync"))
        self.actionOpeningARecentFileNavigatesToItsDirectory.setIcon(icon25)
        self.actionOpeningARecentFileNavigatesToItsDirectory.setMenuRole(QAction.MenuRole.PreferencesRole)
        self.useLastHistoryCommandSearchAction = QAction(MainWindow)
        self.useLastHistoryCommandSearchAction.setObjectName(u"useLastHistoryCommandSearchAction")
        self.useLastHistoryCommandSearchAction.setCheckable(True)
        icon26 = QIcon(QIcon.fromTheme(u"document-open-recent"))
        self.useLastHistoryCommandSearchAction.setIcon(icon26)
        self.actionSynchronize_working_directory_when_opening_a_dropped_file = QAction(MainWindow)
        self.actionSynchronize_working_directory_when_opening_a_dropped_file.setObjectName(u"actionSynchronize_working_directory_when_opening_a_dropped_file")
        self.actionSynchronize_working_directory_when_opening_a_dropped_file.setCheckable(True)
        icon27 = QIcon(QIcon.fromTheme(u"folder-sync"))
        self.actionSynchronize_working_directory_when_opening_a_dropped_file.setIcon(icon27)
        self.actionStandard = QAction(MainWindow)
        self.actionStandard.setObjectName(u"actionStandard")
        self.actionStandard.setCheckable(False)
        self.actionNarrow = QAction(MainWindow)
        self.actionNarrow.setObjectName(u"actionNarrow")
        self.actionShort = QAction(MainWindow)
        self.actionShort.setObjectName(u"actionShort")
        self.actionLong = QAction(MainWindow)
        self.actionLong.setObjectName(u"actionLong")
        self.actionTimeDisplayFormat = QAction(MainWindow)
        self.actionTimeDisplayFormat.setObjectName(u"actionTimeDisplayFormat")
        icon28 = QIcon(QIcon.fromTheme(u"accept_time_event"))
        self.actionTimeDisplayFormat.setIcon(icon28)
        self.actionTreeView = QAction(MainWindow)
        self.actionTreeView.setObjectName(u"actionTreeView")
        self.actionTreeView.setCheckable(True)
        icon29 = QIcon(QIcon.fromTheme(u"view-list-tree"))
        self.actionTreeView.setIcon(icon29)
        self.actionListView = QAction(MainWindow)
        self.actionListView.setObjectName(u"actionListView")
        self.actionListView.setCheckable(True)
        icon30 = QIcon(QIcon.fromTheme(u"view-list-details"))
        self.actionListView.setIcon(icon30)
        self.actionIconView = QAction(MainWindow)
        self.actionIconView.setObjectName(u"actionIconView")
        self.actionIconView.setCheckable(True)
        icon31 = QIcon(QIcon.fromTheme(u"view-list-icons"))
        self.actionIconView.setIcon(icon31)
        self.actionColumnView = QAction(MainWindow)
        self.actionColumnView.setObjectName(u"actionColumnView")
        self.actionColumnView.setCheckable(True)
        icon32 = QIcon(QIcon.fromTheme(u"object-columns"))
        self.actionColumnView.setIcon(icon32)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QSize(0, 0))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 898, 28))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy1)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        icon33 = QIcon(QIcon.fromTheme(u"system-file-manager-symbolic"))
        self.menuFile.setIcon(icon33)
        self.menuImport = QMenu(self.menuFile)
        self.menuImport.setObjectName(u"menuImport")
        self.menuImport.setIcon(icon5)
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        icon34 = QIcon(QIcon.fromTheme(u"help-contents"))
        self.menuHelp.setIcon(icon34)
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        icon35 = QIcon(QIcon.fromTheme(u"quickview"))
        self.menuView.setIcon(icon35)
        self.menuSelected_Image_or_Volume = QMenu(self.menuView)
        self.menuSelected_Image_or_Volume.setObjectName(u"menuSelected_Image_or_Volume")
        icon36 = QIcon(QIcon.fromTheme(u"x-shape-image"))
        self.menuSelected_Image_or_Volume.setIcon(icon36)
        self.menuViewers = QMenu(self.menubar)
        self.menuViewers.setObjectName(u"menuViewers")
        self.menuViewers.setIcon(icon7)
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        icon37 = QIcon(QIcon.fromTheme(u"settings-configure"))
        self.menuSettings.setIcon(icon37)
        self.menuCode_editor = QMenu(self.menuSettings)
        self.menuCode_editor.setObjectName(u"menuCode_editor")
        self.menuCode_editor.setIcon(icon13)
        self.menuFileNavigation = QMenu(self.menuSettings)
        self.menuFileNavigation.setObjectName(u"menuFileNavigation")
        icon38 = QIcon(QIcon.fromTheme(u"file-catalog-symbolic"))
        self.menuFileNavigation.setIcon(icon38)
        self.menuSynchronize_working_directory = QMenu(self.menuFileNavigation)
        self.menuSynchronize_working_directory.setObjectName(u"menuSynchronize_working_directory")
        self.menuSynchronize_working_directory.setIcon(icon27)
        self.menuFileSystemView = QMenu(self.menuFileNavigation)
        self.menuFileSystemView.setObjectName(u"menuFileSystemView")
        self.menuAppearance = QMenu(self.menuSettings)
        self.menuAppearance.setObjectName(u"menuAppearance")
        self.menuAppearance.setIcon(icon11)
        self.menuFonts = QMenu(self.menuAppearance)
        self.menuFonts.setObjectName(u"menuFonts")
        icon39 = QIcon(QIcon.fromTheme(u"font-face"))
        self.menuFonts.setIcon(icon39)
        self.menuIcon_Sizes = QMenu(self.menuAppearance)
        self.menuIcon_Sizes.setObjectName(u"menuIcon_Sizes")
        self.menuIcon_Sizes.setIcon(icon19)
        self.menuConsoles = QMenu(self.menubar)
        self.menuConsoles.setObjectName(u"menuConsoles")
        icon40 = QIcon(QIcon.fromTheme(u"akonadiconsole"))
        self.menuConsoles.setIcon(icon40)
        self.menuScripts = QMenu(self.menubar)
        self.menuScripts.setObjectName(u"menuScripts")
        icon41 = QIcon(QIcon.fromTheme(u"automated-tasks"))
        self.menuScripts.setIcon(icon41)
        self.menuApplications = QMenu(self.menubar)
        self.menuApplications.setObjectName(u"menuApplications")
        icon42 = QIcon(QIcon.fromTheme(u"homerun"))
        self.menuApplications.setIcon(icon42)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidgetWorkspace = QDockWidget(MainWindow)
        self.dockWidgetWorkspace.setObjectName(u"dockWidgetWorkspace")
        sizePolicy.setHeightForWidth(self.dockWidgetWorkspace.sizePolicy().hasHeightForWidth())
        self.dockWidgetWorkspace.setSizePolicy(sizePolicy)
        icon43 = QIcon(QIcon.fromTheme(u"view-multiple-objects"))
        self.dockWidgetWorkspace.setWindowIcon(icon43)
        self.dockWidgetWorkspace.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetWorkspaceContents = QWidget()
        self.dockWidgetWorkspaceContents.setObjectName(u"dockWidgetWorkspaceContents")
        self.verticalLayout_2 = QVBoxLayout(self.dockWidgetWorkspaceContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.copyVarnameToolBtn = QToolButton(self.dockWidgetWorkspaceContents)
        self.copyVarnameToolBtn.setObjectName(u"copyVarnameToolBtn")
        icon44 = QIcon(QIcon.fromTheme(u"edit-copy"))
        self.copyVarnameToolBtn.setIcon(icon44)
        self.copyVarnameToolBtn.setAutoRaise(True)

        self.horizontalLayout_3.addWidget(self.copyVarnameToolBtn)

        self.sendVarnameToConsoleToolBtn = QToolButton(self.dockWidgetWorkspaceContents)
        self.sendVarnameToConsoleToolBtn.setObjectName(u"sendVarnameToConsoleToolBtn")
        icon45 = QIcon(QIcon.fromTheme(u"edit-paste-symbolic"))
        self.sendVarnameToConsoleToolBtn.setIcon(icon45)
        self.sendVarnameToConsoleToolBtn.setAutoRaise(True)

        self.horizontalLayout_3.addWidget(self.sendVarnameToConsoleToolBtn)

        self.renameVarnameToolBtn = QToolButton(self.dockWidgetWorkspaceContents)
        self.renameVarnameToolBtn.setObjectName(u"renameVarnameToolBtn")
        icon46 = QIcon(QIcon.fromTheme(u"edit-rename-symbolic"))
        self.renameVarnameToolBtn.setIcon(icon46)
        self.renameVarnameToolBtn.setAutoRaise(True)

        self.horizontalLayout_3.addWidget(self.renameVarnameToolBtn)

        self.displayVariableToolBtn = QToolButton(self.dockWidgetWorkspaceContents)
        self.displayVariableToolBtn.setObjectName(u"displayVariableToolBtn")
        self.displayVariableToolBtn.setIcon(icon20)
        self.displayVariableToolBtn.setPopupMode(QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.displayVariableToolBtn.setAutoRaise(True)
        self.displayVariableToolBtn.setArrowType(Qt.ArrowType.NoArrow)

        self.horizontalLayout_3.addWidget(self.displayVariableToolBtn)

        self.saveVariableToolBtn = QToolButton(self.dockWidgetWorkspaceContents)
        self.saveVariableToolBtn.setObjectName(u"saveVariableToolBtn")
        icon47 = QIcon(QIcon.fromTheme(u"document-save-symbolic"))
        self.saveVariableToolBtn.setIcon(icon47)
        self.saveVariableToolBtn.setAutoRaise(True)

        self.horizontalLayout_3.addWidget(self.saveVariableToolBtn)

        self.removeSelectedVarsToolBtn = QToolButton(self.dockWidgetWorkspaceContents)
        self.removeSelectedVarsToolBtn.setObjectName(u"removeSelectedVarsToolBtn")
        icon48 = QIcon(QIcon.fromTheme(u"edit-delete-symbolic"))
        self.removeSelectedVarsToolBtn.setIcon(icon48)
        self.removeSelectedVarsToolBtn.setAutoRaise(True)

        self.horizontalLayout_3.addWidget(self.removeSelectedVarsToolBtn)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_3)

        self.clearWorkspaceToolBtn = QToolButton(self.dockWidgetWorkspaceContents)
        self.clearWorkspaceToolBtn.setObjectName(u"clearWorkspaceToolBtn")
        icon49 = QIcon(QIcon.fromTheme(u"edit-clear-all-symbolic"))
        self.clearWorkspaceToolBtn.setIcon(icon49)
        self.clearWorkspaceToolBtn.setAutoRaise(True)

        self.horizontalLayout_3.addWidget(self.clearWorkspaceToolBtn)


        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.workspaceView = QTableView(self.dockWidgetWorkspaceContents)
        self.workspaceView.setObjectName(u"workspaceView")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.workspaceView.sizePolicy().hasHeightForWidth())
        self.workspaceView.setSizePolicy(sizePolicy2)
        self.workspaceView.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.workspaceView.setAcceptDrops(True)
        self.workspaceView.setProperty(u"showDropIndicator", True)
        self.workspaceView.setDragEnabled(True)
        self.workspaceView.setDragDropOverwriteMode(False)
        self.workspaceView.setDragDropMode(QAbstractItemView.DragDropMode.DragOnly)
        self.workspaceView.setDefaultDropAction(Qt.DropAction.IgnoreAction)
        self.workspaceView.setAlternatingRowColors(True)
        self.workspaceView.setShowGrid(False)
        self.workspaceView.setGridStyle(Qt.PenStyle.DotLine)
        self.workspaceView.setSortingEnabled(True)
        self.workspaceView.setWordWrap(False)
        self.workspaceView.horizontalHeader().setCascadingSectionResizes(True)
        self.workspaceView.horizontalHeader().setStretchLastSection(True)
        self.workspaceView.verticalHeader().setVisible(True)
        self.workspaceView.verticalHeader().setProperty(u"showSortIndicator", False)

        self.verticalLayout_2.addWidget(self.workspaceView)

        self.varNameFilterFinderComboBox = QComboBox(self.dockWidgetWorkspaceContents)
        self.varNameFilterFinderComboBox.setObjectName(u"varNameFilterFinderComboBox")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.varNameFilterFinderComboBox.sizePolicy().hasHeightForWidth())
        self.varNameFilterFinderComboBox.setSizePolicy(sizePolicy3)
        self.varNameFilterFinderComboBox.setEditable(True)

        self.verticalLayout_2.addWidget(self.varNameFilterFinderComboBox)

        self.dockWidgetWorkspace.setWidget(self.dockWidgetWorkspaceContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.dockWidgetWorkspace)
        self.dockWidgetHistory = QDockWidget(MainWindow)
        self.dockWidgetHistory.setObjectName(u"dockWidgetHistory")
        sizePolicy.setHeightForWidth(self.dockWidgetHistory.sizePolicy().hasHeightForWidth())
        self.dockWidgetHistory.setSizePolicy(sizePolicy)
        icon50 = QIcon(QIcon.fromTheme(u"folder-recent"))
        self.dockWidgetHistory.setWindowIcon(icon50)
        self.dockWidgetHistory.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetHistoryContents = QWidget()
        self.dockWidgetHistoryContents.setObjectName(u"dockWidgetHistoryContents")
        self.gridLayout_2 = QGridLayout(self.dockWidgetHistoryContents)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.historyCommandsExecuteToolButton = QToolButton(self.dockWidgetHistoryContents)
        self.historyCommandsExecuteToolButton.setObjectName(u"historyCommandsExecuteToolButton")
        icon51 = QIcon(QIcon.fromTheme(u"run-build"))
        self.historyCommandsExecuteToolButton.setIcon(icon51)
        self.historyCommandsExecuteToolButton.setAutoRaise(True)

        self.horizontalLayout_4.addWidget(self.historyCommandsExecuteToolButton)

        self.historyCommandsToConsoleToolButton = QToolButton(self.dockWidgetHistoryContents)
        self.historyCommandsToConsoleToolButton.setObjectName(u"historyCommandsToConsoleToolButton")
        self.historyCommandsToConsoleToolButton.setIcon(icon3)
        self.historyCommandsToConsoleToolButton.setAutoRaise(True)

        self.horizontalLayout_4.addWidget(self.historyCommandsToConsoleToolButton)

        self.copyHistoryCommands = QToolButton(self.dockWidgetHistoryContents)
        self.copyHistoryCommands.setObjectName(u"copyHistoryCommands")
        self.copyHistoryCommands.setIcon(icon44)
        self.copyHistoryCommands.setAutoRaise(True)

        self.horizontalLayout_4.addWidget(self.copyHistoryCommands)

        self.saveHistoryToolbutton = QToolButton(self.dockWidgetHistoryContents)
        self.saveHistoryToolbutton.setObjectName(u"saveHistoryToolbutton")
        self.saveHistoryToolbutton.setIcon(icon1)
        self.saveHistoryToolbutton.setAutoRaise(True)

        self.horizontalLayout_4.addWidget(self.saveHistoryToolbutton)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_4)


        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)

        self.historyTreeWidget = QTreeWidget(self.dockWidgetHistoryContents)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(1, u"2")
        __qtreewidgetitem.setText(0, u"1")
        self.historyTreeWidget.setHeaderItem(__qtreewidgetitem)
        self.historyTreeWidget.setObjectName(u"historyTreeWidget")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.historyTreeWidget.sizePolicy().hasHeightForWidth())
        self.historyTreeWidget.setSizePolicy(sizePolicy4)
        self.historyTreeWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.historyTreeWidget.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.historyTreeWidget.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.historyTreeWidget.setProperty(u"showDropIndicator", False)
        self.historyTreeWidget.setDragEnabled(True)
        self.historyTreeWidget.setDragDropMode(QAbstractItemView.DragDropMode.DragOnly)
        self.historyTreeWidget.setAlternatingRowColors(True)
        self.historyTreeWidget.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.historyTreeWidget.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectItems)
        self.historyTreeWidget.setColumnCount(2)
        self.historyTreeWidget.header().setVisible(True)
        self.historyTreeWidget.header().setCascadingSectionResizes(True)
        self.historyTreeWidget.header().setMinimumSectionSize(100)
        self.historyTreeWidget.header().setDefaultSectionSize(100)
        self.historyTreeWidget.header().setHighlightSections(True)
        self.historyTreeWidget.header().setProperty(u"showSortIndicator", False)
        self.historyTreeWidget.header().setStretchLastSection(True)

        self.gridLayout_2.addWidget(self.historyTreeWidget, 1, 0, 1, 1)

        self.commandHistoryFinderComboBox = QComboBox(self.dockWidgetHistoryContents)
        self.commandHistoryFinderComboBox.setObjectName(u"commandHistoryFinderComboBox")
        sizePolicy3.setHeightForWidth(self.commandHistoryFinderComboBox.sizePolicy().hasHeightForWidth())
        self.commandHistoryFinderComboBox.setSizePolicy(sizePolicy3)
        self.commandHistoryFinderComboBox.setEditable(True)

        self.gridLayout_2.addWidget(self.commandHistoryFinderComboBox, 2, 0, 1, 1)

        self.dockWidgetHistory.setWidget(self.dockWidgetHistoryContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.dockWidgetHistory)
        self.dockWidgetFileSystem = QDockWidget(MainWindow)
        self.dockWidgetFileSystem.setObjectName(u"dockWidgetFileSystem")
        sizePolicy.setHeightForWidth(self.dockWidgetFileSystem.sizePolicy().hasHeightForWidth())
        self.dockWidgetFileSystem.setSizePolicy(sizePolicy)
        icon52 = QIcon(QIcon.fromTheme(u"folder"))
        self.dockWidgetFileSystem.setWindowIcon(icon52)
        self.dockWidgetFileSystem.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetFloatable|QDockWidget.DockWidgetFeature.DockWidgetMovable)
        self.dockWidgetFileSystemContents = QWidget()
        self.dockWidgetFileSystemContents.setObjectName(u"dockWidgetFileSystemContents")
        self.gridLayout_5 = QGridLayout(self.dockWidgetFileSystemContents)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)
        self.dirHomeBtn = QToolButton(self.dockWidgetFileSystemContents)
        self.dirHomeBtn.setObjectName(u"dirHomeBtn")
        icon53 = QIcon(QIcon.fromTheme(u"go-home"))
        self.dirHomeBtn.setIcon(icon53)
        self.dirHomeBtn.setAutoRaise(True)

        self.horizontalLayout.addWidget(self.dirHomeBtn)

        self.dirBackBtn = QToolButton(self.dockWidgetFileSystemContents)
        self.dirBackBtn.setObjectName(u"dirBackBtn")
        icon54 = QIcon(QIcon.fromTheme(u"go-previous"))
        self.dirBackBtn.setIcon(icon54)
        self.dirBackBtn.setAutoRaise(True)
        self.dirBackBtn.setArrowType(Qt.ArrowType.LeftArrow)

        self.horizontalLayout.addWidget(self.dirBackBtn)

        self.dirFwdBtn = QToolButton(self.dockWidgetFileSystemContents)
        self.dirFwdBtn.setObjectName(u"dirFwdBtn")
        icon55 = QIcon(QIcon.fromTheme(u"go-next"))
        self.dirFwdBtn.setIcon(icon55)
        self.dirFwdBtn.setAutoRaise(True)
        self.dirFwdBtn.setArrowType(Qt.ArrowType.RightArrow)

        self.horizontalLayout.addWidget(self.dirFwdBtn)

        self.dirUpBtn = QToolButton(self.dockWidgetFileSystemContents)
        self.dirUpBtn.setObjectName(u"dirUpBtn")
        icon56 = QIcon(QIcon.fromTheme(u"go-up"))
        self.dirUpBtn.setIcon(icon56)
        self.dirUpBtn.setAutoRaise(True)
        self.dirUpBtn.setArrowType(Qt.ArrowType.UpArrow)

        self.horizontalLayout.addWidget(self.dirUpBtn)

        self.selDirBtn = QToolButton(self.dockWidgetFileSystemContents)
        self.selDirBtn.setObjectName(u"selDirBtn")
        self.selDirBtn.setIcon(icon10)
        self.selDirBtn.setAutoRaise(True)

        self.horizontalLayout.addWidget(self.selDirBtn)

        self.systemOpenFolderBtn = QToolButton(self.dockWidgetFileSystemContents)
        self.systemOpenFolderBtn.setObjectName(u"systemOpenFolderBtn")
        self.systemOpenFolderBtn.setIcon(icon10)
        self.systemOpenFolderBtn.setAutoRaise(True)

        self.horizontalLayout.addWidget(self.systemOpenFolderBtn)

        self.systemOpenParentFolderBtn = QToolButton(self.dockWidgetFileSystemContents)
        self.systemOpenParentFolderBtn.setObjectName(u"systemOpenParentFolderBtn")
        icon57 = QIcon(QIcon.fromTheme(u"go-parent-folder"))
        self.systemOpenParentFolderBtn.setIcon(icon57)
        self.systemOpenParentFolderBtn.setAutoRaise(True)

        self.horizontalLayout.addWidget(self.systemOpenParentFolderBtn)

        self.openTermBtn = QToolButton(self.dockWidgetFileSystemContents)
        self.openTermBtn.setObjectName(u"openTermBtn")
        self.openTermBtn.setIcon(icon3)
        self.openTermBtn.setAutoRaise(True)

        self.horizontalLayout.addWidget(self.openTermBtn)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.fileSystemViewToolButton = QToolButton(self.dockWidgetFileSystemContents)
        self.fileSystemViewToolButton.setObjectName(u"fileSystemViewToolButton")
        self.fileSystemViewToolButton.setIcon(icon43)
        self.fileSystemViewToolButton.setPopupMode(QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.fileSystemViewToolButton.setAutoRaise(True)
        self.fileSystemViewToolButton.setArrowType(Qt.ArrowType.NoArrow)

        self.horizontalLayout.addWidget(self.fileSystemViewToolButton)

        self.toggleFilesFilterToolBtn = QToolButton(self.dockWidgetFileSystemContents)
        self.toggleFilesFilterToolBtn.setObjectName(u"toggleFilesFilterToolBtn")
        icon58 = QIcon(QIcon.fromTheme(u"view-filter"))
        self.toggleFilesFilterToolBtn.setIcon(icon58)
        self.toggleFilesFilterToolBtn.setCheckable(True)
        self.toggleFilesFilterToolBtn.setAutoRaise(True)
        self.toggleFilesFilterToolBtn.setArrowType(Qt.ArrowType.NoArrow)

        self.horizontalLayout.addWidget(self.toggleFilesFilterToolBtn)


        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.navigator = UrlNavigator(self.dockWidgetFileSystemContents)
        self.navigator.setObjectName(u"navigator")

        self.gridLayout_5.addWidget(self.navigator, 1, 0, 1, 1)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.fileSystemViewStackedWidget = QStackedWidget(self.dockWidgetFileSystemContents)
        self.fileSystemViewStackedWidget.setObjectName(u"fileSystemViewStackedWidget")
        self.fileSystemTreeViewPage = QWidget()
        self.fileSystemTreeViewPage.setObjectName(u"fileSystemTreeViewPage")
        self.gridLayout_4 = QGridLayout(self.fileSystemTreeViewPage)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.fileSystemTreeView = QTreeView(self.fileSystemTreeViewPage)
        self.fileSystemTreeView.setObjectName(u"fileSystemTreeView")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(1)
        sizePolicy5.setHeightForWidth(self.fileSystemTreeView.sizePolicy().hasHeightForWidth())
        self.fileSystemTreeView.setSizePolicy(sizePolicy5)
        self.fileSystemTreeView.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.fileSystemTreeView.setAcceptDrops(False)
        self.fileSystemTreeView.setFrameShape(QFrame.Shape.StyledPanel)
        self.fileSystemTreeView.setFrameShadow(QFrame.Shadow.Sunken)
        self.fileSystemTreeView.setLineWidth(1)
        self.fileSystemTreeView.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.fileSystemTreeView.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.fileSystemTreeView.setTabKeyNavigation(True)
        self.fileSystemTreeView.setProperty(u"showDropIndicator", False)
        self.fileSystemTreeView.setDragEnabled(True)
        self.fileSystemTreeView.setDragDropMode(QAbstractItemView.DragDropMode.DragOnly)
        self.fileSystemTreeView.setAlternatingRowColors(True)
        self.fileSystemTreeView.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.fileSystemTreeView.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectItems)
        self.fileSystemTreeView.setIconSize(QSize(16, 16))
        self.fileSystemTreeView.setUniformRowHeights(True)
        self.fileSystemTreeView.setSortingEnabled(True)
        self.fileSystemTreeView.header().setCascadingSectionResizes(True)
        self.fileSystemTreeView.header().setHighlightSections(True)
        self.fileSystemTreeView.header().setProperty(u"showSortIndicator", True)
        self.fileSystemTreeView.header().setStretchLastSection(True)

        self.gridLayout_4.addWidget(self.fileSystemTreeView, 0, 0, 1, 1)

        self.fileSystemViewStackedWidget.addWidget(self.fileSystemTreeViewPage)
        self.fileSystemListViewPage = QWidget()
        self.fileSystemListViewPage.setObjectName(u"fileSystemListViewPage")
        self.gridLayout_3 = QGridLayout(self.fileSystemListViewPage)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.fileSystemListView = QListView(self.fileSystemListViewPage)
        self.fileSystemListView.setObjectName(u"fileSystemListView")
        self.fileSystemListView.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.fileSystemListView.setEditTriggers(QAbstractItemView.EditTrigger.EditKeyPressed)
        self.fileSystemListView.setDragDropMode(QAbstractItemView.DragDropMode.DragOnly)
        self.fileSystemListView.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)

        self.gridLayout_3.addWidget(self.fileSystemListView, 0, 0, 1, 1)

        self.fileSystemViewStackedWidget.addWidget(self.fileSystemListViewPage)
        self.fileSystemColumnViewPage = QWidget()
        self.fileSystemColumnViewPage.setObjectName(u"fileSystemColumnViewPage")
        self.gridLayout = QGridLayout(self.fileSystemColumnViewPage)
        self.gridLayout.setObjectName(u"gridLayout")
        self.fileSystemColumnView = QColumnView(self.fileSystemColumnViewPage)
        self.fileSystemColumnView.setObjectName(u"fileSystemColumnView")
        self.fileSystemColumnView.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.fileSystemColumnView.setEditTriggers(QAbstractItemView.EditTrigger.EditKeyPressed)
        self.fileSystemColumnView.setDragEnabled(True)
        self.fileSystemColumnView.setDragDropMode(QAbstractItemView.DragDropMode.DragOnly)
        self.fileSystemColumnView.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectItems)

        self.gridLayout.addWidget(self.fileSystemColumnView, 0, 0, 1, 1)

        self.fileSystemViewStackedWidget.addWidget(self.fileSystemColumnViewPage)

        self.verticalLayout.addWidget(self.fileSystemViewStackedWidget)

        self.filesFilterFrame = QFrame(self.dockWidgetFileSystemContents)
        self.filesFilterFrame.setObjectName(u"filesFilterFrame")
        self.filesFilterFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.filesFilterFrame.setFrameShadow(QFrame.Shadow.Plain)
        self.filesFilterFrame.setLineWidth(0)
        self.horizontalLayout_2 = QHBoxLayout(self.filesFilterFrame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.filesFilterLabel = QLabel(self.filesFilterFrame)
        self.filesFilterLabel.setObjectName(u"filesFilterLabel")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.filesFilterLabel.sizePolicy().hasHeightForWidth())
        self.filesFilterLabel.setSizePolicy(sizePolicy6)

        self.horizontalLayout_2.addWidget(self.filesFilterLabel)

        self.horizontalSpacer = QSpacerItem(13, 17, QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)

        self.fileSystemFilter = QComboBox(self.filesFilterFrame)
        self.fileSystemFilter.setObjectName(u"fileSystemFilter")
        sizePolicy7 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.fileSystemFilter.sizePolicy().hasHeightForWidth())
        self.fileSystemFilter.setSizePolicy(sizePolicy7)
        self.fileSystemFilter.setEditable(True)
        self.fileSystemFilter.setInsertPolicy(QComboBox.InsertPolicy.InsertAtTop)

        self.horizontalLayout_2.addWidget(self.fileSystemFilter)

        self.hideFilteredOutnamesToolButton = QToolButton(self.filesFilterFrame)
        self.hideFilteredOutnamesToolButton.setObjectName(u"hideFilteredOutnamesToolButton")
        self.hideFilteredOutnamesToolButton.setIcon(icon24)
        self.hideFilteredOutnamesToolButton.setCheckable(True)
        self.hideFilteredOutnamesToolButton.setAutoRaise(True)

        self.horizontalLayout_2.addWidget(self.hideFilteredOutnamesToolButton)

        self.hideFilesFilterToolBtn = QToolButton(self.filesFilterFrame)
        self.hideFilesFilterToolBtn.setObjectName(u"hideFilesFilterToolBtn")
        self.hideFilesFilterToolBtn.setEnabled(True)
        icon59 = QIcon(QIcon.fromTheme(u"window-close"))
        self.hideFilesFilterToolBtn.setIcon(icon59)
        self.hideFilesFilterToolBtn.setAutoRaise(True)

        self.horizontalLayout_2.addWidget(self.hideFilesFilterToolBtn)


        self.verticalLayout.addWidget(self.filesFilterFrame)


        self.gridLayout_5.addLayout(self.verticalLayout, 2, 0, 1, 1)

        self.dockWidgetFileSystem.setWidget(self.dockWidgetFileSystemContents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.dockWidgetFileSystem)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        sizePolicy3.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy3)
        self.toolBar.setAcceptDrops(False)
        self.toolBar.setIconSize(QSize(22, 22))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonFollowStyle)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
#if QT_CONFIG(shortcut)
        self.filesFilterLabel.setBuddy(self.fileSystemFilter)
#endif // QT_CONFIG(shortcut)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuViewers.menuAction())
        self.menubar.addAction(self.menuConsoles.menuAction())
        self.menubar.addAction(self.menuScripts.menuAction())
        self.menubar.addAction(self.menuApplications.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionChange_Working_Directory)
        self.menuFile.addAction(self.actionReload_Plugins)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuImport.addAction(self.actionImport_PrairieView_data)
        self.menuHelp.addAction(self.actionPython_help)
        self.menuHelp.addAction(self.actionHelp_On_Console)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionAbout_Components)
        self.menuHelp.addAction(self.actionLicense)
        self.menuView.addAction(self.menuSelected_Image_or_Volume.menuAction())
        self.menuSelected_Image_or_Volume.addAction(self.actionView_Data_New_Window)
        self.menuSelected_Image_or_Volume.addAction(self.actionView_Data)
        self.menuSelected_Image_or_Volume.addAction(self.actionDisplay_In_Console)
        self.menuSettings.addAction(self.actionAuto_launch_Script_Manager)
        self.menuSettings.addAction(self.menuCode_editor.menuAction())
        self.menuSettings.addAction(self.actionAuto_delete_viewer)
        self.menuSettings.addAction(self.actionSet_user_plugins_directory)
        self.menuSettings.addAction(self.actionConfigure_external_HDF_viewer)
        self.menuSettings.addAction(self.useLastHistoryCommandSearchAction)
        self.menuSettings.addAction(self.actionUseShellAutomagic)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.menuAppearance.menuAction())
        self.menuSettings.addAction(self.menuFileNavigation.menuAction())
        self.menuCode_editor.addAction(self.actionChoose_code_editor)
        self.menuCode_editor.addAction(self.actionUse_system_s_default_code_editor)
        self.menuFileNavigation.addAction(self.actionUse_Native_Menu_Bar)
        self.menuFileNavigation.addAction(self.actionUse_New_Navigator_Look)
        self.menuFileNavigation.addAction(self.actionTimeDisplayFormat)
        self.menuFileNavigation.addAction(self.actionHide_Filtered_out_File_Names)
        self.menuFileNavigation.addAction(self.menuSynchronize_working_directory.menuAction())
        self.menuFileNavigation.addAction(self.menuFileSystemView.menuAction())
        self.menuSynchronize_working_directory.addSeparator()
        self.menuSynchronize_working_directory.addAction(self.actionOpeningARecentFileNavigatesToItsDirectory)
        self.menuSynchronize_working_directory.addAction(self.actionSynchronize_working_directory_when_opening_a_dropped_file)
        self.menuFileSystemView.addAction(self.actionTreeView)
        self.menuFileSystemView.addAction(self.actionListView)
        self.menuFileSystemView.addAction(self.actionIconView)
        self.menuFileSystemView.addAction(self.actionColumnView)
        self.menuAppearance.addAction(self.actionGUI_Style)
        self.menuAppearance.addAction(self.actionTool_Button_Style)
        self.menuAppearance.addAction(self.menuFonts.menuAction())
        self.menuAppearance.addAction(self.menuIcon_Sizes.menuAction())
        self.menuFonts.addAction(self.actionUse_system_default_font)
        self.menuFonts.addAction(self.actionCommandHistoryFont)
        self.menuFonts.addAction(self.actionWorkplaceFont)
        self.menuIcon_Sizes.addAction(self.actionSet_Icon_Size)
        self.menuIcon_Sizes.addAction(self.actionWorkspaceIconSize)
        self.menuIcon_Sizes.addAction(self.actionFile_SystemIconSize)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionChange_Working_Directory)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)

        self.fileSystemViewStackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Scipyen", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"&Save ...", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"Save", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave.setStatusTip(QCoreApplication.translate("MainWindow", u"Save (export data)", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionSave.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>When several objects are selected in the workspace (User Variables tab) this will save them as HDF5 files named after the object name (symbol) in the workspace.</p><p><br/></p><p>When only one object is selected in the workspace, will show a dialog for selecting the file name and a file type (where appropriate) for saving the object.</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action_Console.setText(QCoreApplication.translate("MainWindow", u"&Console", None))
        self.actionRestore_Workspace.setText(QCoreApplication.translate("MainWindow", u"&Restore Workspace", None))
        self.actionHelp_On_Console.setText(QCoreApplication.translate("MainWindow", u"&On Console", None))
        self.actionImport_PrairieView_data.setText(QCoreApplication.translate("MainWindow", u"PrairieView data", None))
        self.actionImport_XY_Raster_Scan_File.setText(QCoreApplication.translate("MainWindow", u"&XY Raster Scan", None))
        self.actionImport_Protocol_File.setText(QCoreApplication.translate("MainWindow", u"&Protocol", None))
        self.actionOpen_Image_File.setText(QCoreApplication.translate("MainWindow", u"&Image", None))
        self.actionOpen_Scan_Data_File.setText(QCoreApplication.translate("MainWindow", u"&Scan Data", None))
        self.actionView_Data_New_Window.setText(QCoreApplication.translate("MainWindow", u"&In New Window", None))
        self.actionView_Data.setText(QCoreApplication.translate("MainWindow", u"In &Current Window", None))
        self.actionReload_Plugins.setText(QCoreApplication.translate("MainWindow", u"&Reload Plugins", None))
        self.actionOpen_Image_File_Using_BioFormats.setText(QCoreApplication.translate("MainWindow", u"Image &Using BioFormats", None))
        self.actionChange_Working_Directory.setText(QCoreApplication.translate("MainWindow", u"&Select Working Directory", None))
#if QT_CONFIG(statustip)
        self.actionChange_Working_Directory.setStatusTip(QCoreApplication.translate("MainWindow", u"Select working directory", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionChange_Working_Directory.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew_Signal_Viewer.setText(QCoreApplication.translate("MainWindow", u"New &Signal Viewer", None))
        self.actionNew_Image_Viewer.setText(QCoreApplication.translate("MainWindow", u"&New Image Viewer", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"&Open...", None))
#if QT_CONFIG(tooltip)
        self.actionOpen.setToolTip(QCoreApplication.translate("MainWindow", u"Open (click on arrow to the right to reveal recently opened files; hold SHIFT to ALSO change to directory of the recent file)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionOpen.setStatusTip(QCoreApplication.translate("MainWindow", u"Opens selected files in the file system browser or via a dialog", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionOpen.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Opens the selected file(s) in the File System tab, or presents an file chooser dialog when no files are selected.</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen_Files.setText(QCoreApplication.translate("MainWindow", u"Open &Files...", None))
        self.actionSave_pickle.setText(QCoreApplication.translate("MainWindow", u"Save (&pickle) selected variables", None))
        self.actionScriptRun.setText(QCoreApplication.translate("MainWindow", u"&Run...", None))
        self.actionScriptToConsole.setText(QCoreApplication.translate("MainWindow", u"&To console...", None))
        self.actionConsole_font.setText(QCoreApplication.translate("MainWindow", u"Console font...", None))
        self.actionEditor.setText(QCoreApplication.translate("MainWindow", u"Editor", None))
        self.actionNewViewer.setText(QCoreApplication.translate("MainWindow", u"New...", None))
        self.actionExternal_IPython.setText(QCoreApplication.translate("MainWindow", u"External IPython", None))
        self.actionConsole.setText(QCoreApplication.translate("MainWindow", u"Console", None))
        self.actionExternalIPython.setText(QCoreApplication.translate("MainWindow", u"External IPython", None))
        self.actionExternalNrnIPython.setText(QCoreApplication.translate("MainWindow", u"External IPython for Neuron", None))
        self.actionConsole_Client_for_Neuron.setText(QCoreApplication.translate("MainWindow", u"Console Client wirh Neuron IPython", None))
        self.actionRunning_IPython.setText(QCoreApplication.translate("MainWindow", u"Choose kernel...", None))
        self.actionRunning_IPython_for_Neuron.setText(QCoreApplication.translate("MainWindow", u"Choose kernel and launch Neuron", None))
        self.actionGUI_Style.setText(QCoreApplication.translate("MainWindow", u"GUI Style...", None))
        self.actionAuto_launch_Script_Manager.setText(QCoreApplication.translate("MainWindow", u"Auto-launch Script Manager", None))
        self.actionChoose_code_editor.setText(QCoreApplication.translate("MainWindow", u"Choose code editor", None))
        self.actionUse_system_s_default_code_editor.setText(QCoreApplication.translate("MainWindow", u"Use system's default code editor", None))
        self.actionAuto_delete_viewer.setText(QCoreApplication.translate("MainWindow", u"Auto-delete viewers", None))
#if QT_CONFIG(tooltip)
        self.actionAuto_delete_viewer.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Remove viewer when closed</p><p>(does not apply to matplotlib figures)</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionAuto_delete_viewer.setStatusTip(QCoreApplication.translate("MainWindow", u"Remove viewer when closed", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionAuto_delete_viewer.setWhatsThis(QCoreApplication.translate("MainWindow", u"When a viewer is closed , also remove it from the user workspace", None))
#endif // QT_CONFIG(whatsthis)
        self.actionOpen_System_Terminal.setText(QCoreApplication.translate("MainWindow", u"Open System Terminal", None))
#if QT_CONFIG(tooltip)
        self.actionOpen_System_Terminal.setToolTip(QCoreApplication.translate("MainWindow", u"Open system terminal", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionOpen_System_Terminal.setStatusTip(QCoreApplication.translate("MainWindow", u"Open system terminal", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionOpen_System_Terminal.setWhatsThis(QCoreApplication.translate("MainWindow", u"Open system terminal", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(shortcut)
        self.actionOpen_System_Terminal.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.actionSet_user_plugins_directory.setText(QCoreApplication.translate("MainWindow", u"Set user plugins directory", None))
        self.actionImport_Electrophysiology_File.setText(QCoreApplication.translate("MainWindow", u"&Electrophysiology", None))
        self.actionRecent.setText(QCoreApplication.translate("MainWindow", u"Recent", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
#if QT_CONFIG(shortcut)
        self.actionAbout.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+/", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout_Components.setText(QCoreApplication.translate("MainWindow", u"About Components", None))
        self.actionLicense.setText(QCoreApplication.translate("MainWindow", u"License", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.actionSet_Icon_Size.setText(QCoreApplication.translate("MainWindow", u"Buttons", None))
#if QT_CONFIG(tooltip)
        self.actionSet_Icon_Size.setToolTip(QCoreApplication.translate("MainWindow", u"Set Buttons Icon Size", None))
#endif // QT_CONFIG(tooltip)
        self.actionConfigure_external_HDF_viewer.setText(QCoreApplication.translate("MainWindow", u"Configure external HDF viewer...", None))
        self.actionUse_system_default_font.setText(QCoreApplication.translate("MainWindow", u"Use system default", None))
        self.actionWorkplaceFont.setText(QCoreApplication.translate("MainWindow", u"Workplace Font...", None))
        self.actionCommandHistoryFont.setText(QCoreApplication.translate("MainWindow", u"Command History Font...", None))
        self.actionDisplay_In_Console.setText(QCoreApplication.translate("MainWindow", u"Display In Console", None))
#if QT_CONFIG(statustip)
        self.actionDisplay_In_Console.setStatusTip(QCoreApplication.translate("MainWindow", u"Display In Console", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionDisplay_In_Console.setWhatsThis(QCoreApplication.translate("MainWindow", u"Display In Console", None))
#endif // QT_CONFIG(whatsthis)
        self.actionWorkspaceIconSize.setText(QCoreApplication.translate("MainWindow", u"Workspace", None))
        self.actionFile_SystemIconSize.setText(QCoreApplication.translate("MainWindow", u"File System", None))
        self.actionUse_Native_Menu_Bar.setText(QCoreApplication.translate("MainWindow", u"Use Native Menu Bar", None))
        self.actionUse_New_Navigator_Look.setText(QCoreApplication.translate("MainWindow", u"Use New Navigator Look", None))
        self.actionUseShellAutomagic.setText(QCoreApplication.translate("MainWindow", u"Use Shell Automagic", None))
        self.actionHide_Filtered_out_File_Names.setText(QCoreApplication.translate("MainWindow", u"Hide Filtered-out File Names", None))
#if QT_CONFIG(tooltip)
        self.actionHide_Filtered_out_File_Names.setToolTip(QCoreApplication.translate("MainWindow", u"Hide non-matching file names when file names filter is used in the File System view", None))
#endif // QT_CONFIG(tooltip)
        self.actionTool_Button_Style.setText(QCoreApplication.translate("MainWindow", u"Tool Button Style...", None))
        self.actionPython_help.setText(QCoreApplication.translate("MainWindow", u"Help", None))
#if QT_CONFIG(statustip)
        self.actionPython_help.setStatusTip(QCoreApplication.translate("MainWindow", u"Python language help", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionPython_help.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Brings up a window to access the help systems of Python and IPython independently of (and in parallel to) the Scipyen's console.</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(shortcut)
        self.actionPython_help.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpeningARecentFileNavigatesToItsDirectory.setText(QCoreApplication.translate("MainWindow", u"When opening a recent file", None))
#if QT_CONFIG(tooltip)
        self.actionOpeningARecentFileNavigatesToItsDirectory.setToolTip(QCoreApplication.translate("MainWindow", u"Check this to enable navigating to the directory of a recent file uppon opening it successfully", None))
#endif // QT_CONFIG(tooltip)
        self.useLastHistoryCommandSearchAction.setText(QCoreApplication.translate("MainWindow", u"Show Last Command Search at Startup", None))
        self.actionSynchronize_working_directory_when_opening_a_dropped_file.setText(QCoreApplication.translate("MainWindow", u"When opening a dropped file", None))
        self.actionStandard.setText(QCoreApplication.translate("MainWindow", u"Standard", None))
        self.actionNarrow.setText(QCoreApplication.translate("MainWindow", u"Narrow", None))
        self.actionShort.setText(QCoreApplication.translate("MainWindow", u"Short", None))
        self.actionLong.setText(QCoreApplication.translate("MainWindow", u"Long", None))
        self.actionTimeDisplayFormat.setText(QCoreApplication.translate("MainWindow", u"Time Display Format", None))
        self.actionTreeView.setText(QCoreApplication.translate("MainWindow", u"Tree View", None))
        self.actionListView.setText(QCoreApplication.translate("MainWindow", u"List View", None))
        self.actionIconView.setText(QCoreApplication.translate("MainWindow", u"Icon View", None))
        self.actionColumnView.setText(QCoreApplication.translate("MainWindow", u"Column View", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"Fi&le", None))
        self.menuImport.setTitle(QCoreApplication.translate("MainWindow", u"&Import", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Hel&p", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuSelected_Image_or_Volume.setTitle(QCoreApplication.translate("MainWindow", u"&Selected Variable", None))
        self.menuViewers.setTitle(QCoreApplication.translate("MainWindow", u"Windows", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuCode_editor.setTitle(QCoreApplication.translate("MainWindow", u"Code editor", None))
        self.menuFileNavigation.setTitle(QCoreApplication.translate("MainWindow", u"File System Navigation", None))
        self.menuSynchronize_working_directory.setTitle(QCoreApplication.translate("MainWindow", u"Synchronize working directory", None))
        self.menuFileSystemView.setTitle(QCoreApplication.translate("MainWindow", u"File System View", None))
        self.menuAppearance.setTitle(QCoreApplication.translate("MainWindow", u"Appearance", None))
        self.menuFonts.setTitle(QCoreApplication.translate("MainWindow", u"Fonts...", None))
        self.menuIcon_Sizes.setTitle(QCoreApplication.translate("MainWindow", u"Icon Sizes", None))
        self.menuConsoles.setTitle(QCoreApplication.translate("MainWindow", u"Consoles", None))
        self.menuScripts.setTitle(QCoreApplication.translate("MainWindow", u"Scripts", None))
        self.menuApplications.setTitle(QCoreApplication.translate("MainWindow", u"Applications", None))
#if QT_CONFIG(tooltip)
        self.dockWidgetWorkspace.setToolTip(QCoreApplication.translate("MainWindow", u"Scipyen's workspace table", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dockWidgetWorkspace.setStatusTip(QCoreApplication.translate("MainWindow", u"Scipyen's workspace table", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.dockWidgetWorkspace.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>A table view with user's variables in Scipyen's workspace.</p><p><span style=\" font-weight:600;\">CAUTION:</span></p><p><span style=\" font-weight:400;\">Not all variables are visible. Notable hidden variables are: `_`, `__`, and objects created at start up (imported modules, functions and variables which are NOT necessarily global). </span></p><p><span style=\" font-weight:400;\">To see all the contents of the workspace at any time, execute `dir()` in Scipyen's console.</span></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.dockWidgetWorkspace.setWindowTitle(QCoreApplication.translate("MainWindow", u"&User Variables", None))
#if QT_CONFIG(tooltip)
        self.copyVarnameToolBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Copy name", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.copyVarnameToolBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Copy name", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.copyVarnameToolBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Copy name", None))
#endif // QT_CONFIG(whatsthis)
        self.copyVarnameToolBtn.setText(QCoreApplication.translate("MainWindow", u"Copy name", None))
#if QT_CONFIG(tooltip)
        self.sendVarnameToConsoleToolBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Send name to console", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.sendVarnameToConsoleToolBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Send name to console", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.sendVarnameToConsoleToolBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Send name to console", None))
#endif // QT_CONFIG(whatsthis)
        self.sendVarnameToConsoleToolBtn.setText(QCoreApplication.translate("MainWindow", u"Copy to console", None))
#if QT_CONFIG(tooltip)
        self.renameVarnameToolBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Rename", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.renameVarnameToolBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Rename", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.renameVarnameToolBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Rename", None))
#endif // QT_CONFIG(whatsthis)
        self.renameVarnameToolBtn.setText(QCoreApplication.translate("MainWindow", u"Rename", None))
#if QT_CONFIG(tooltip)
        self.displayVariableToolBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Display object in console", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.displayVariableToolBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Display object in console", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.displayVariableToolBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Display object in console", None))
#endif // QT_CONFIG(whatsthis)
        self.displayVariableToolBtn.setText(QCoreApplication.translate("MainWindow", u"Display in console", None))
#if QT_CONFIG(tooltip)
        self.saveVariableToolBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Save objects to disk (pickle); press & hold Shift to save as HDF5", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.saveVariableToolBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Save objects to disk", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.saveVariableToolBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Save objects to disk (pickle); press & hold Shift to save as HDF5", None))
#endif // QT_CONFIG(whatsthis)
        self.saveVariableToolBtn.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(tooltip)
        self.removeSelectedVarsToolBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Remove selected objects", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.removeSelectedVarsToolBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Remove selected objects", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.removeSelectedVarsToolBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Remove selected objects", None))
#endif // QT_CONFIG(whatsthis)
        self.removeSelectedVarsToolBtn.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
#if QT_CONFIG(tooltip)
        self.clearWorkspaceToolBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Clear workspace", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.clearWorkspaceToolBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Clear workspace", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.clearWorkspaceToolBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Clear workspace", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.clearWorkspaceToolBtn.setAccessibleName(QCoreApplication.translate("MainWindow", u"Clear workspace", None))
#endif // QT_CONFIG(accessibility)
        self.clearWorkspaceToolBtn.setText(QCoreApplication.translate("MainWindow", u"Clear workspace", None))
#if QT_CONFIG(tooltip)
        self.workspaceView.setToolTip(QCoreApplication.translate("MainWindow", u"<html>\n"
"<head/>\n"
"<body>\n"
"<ul>\n"
"<li>Left mouse buttons:\n"
"<ul>\n"
"<li>single click selects</li>\n"
"<li>double click show variable in the default Scipyen viewer for the variable type</li>\n"
"</ul>\n"
"</li>\n"
"<li>Right mouse button click for context menu</li>\n"
"</ul>\n"
"</body>\n"
"</html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.workspaceView.setStatusTip(QCoreApplication.translate("MainWindow", u"Left click to select; left double click to display; right click for context menu.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.workspaceView.setWhatsThis(QCoreApplication.translate("MainWindow", u"Left button click selects (press SHIFT for continuous, CTRL for extended selection). \n"
"\n"
"Left button double-click opens data in viewer (SHIFT for a new viewer) or displays data in console if no appropriate viewer exists.\n"
"\n"
"Right button click opens context menu with more actions.\n"
"\n"
"NOTE: you can click anywhere in the row to select", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.varNameFilterFinderComboBox.setToolTip(QCoreApplication.translate("MainWindow", u"Find variable by name using regular expressions. Pres ENTER to remember this expression.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.varNameFilterFinderComboBox.setStatusTip(QCoreApplication.translate("MainWindow", u"Find variable by name using regular expressions. Pres ENTER to remember this expression.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.varNameFilterFinderComboBox.setWhatsThis(QCoreApplication.translate("MainWindow", u"Find variable by name using regular expressions. Pres ENTER to remember this expression.", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.dockWidgetHistory.setToolTip(QCoreApplication.translate("MainWindow", u"History of console commands & statements", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dockWidgetHistory.setStatusTip(QCoreApplication.translate("MainWindow", u"History of console commands & statements", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.dockWidgetHistory.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>The history of commands and statements executed at Scipyen's console, and grouped by session, (start and end times shown).</p><p>Sessions without an end time are those where Scipyen was suddenly aborted.</p><p>You can copy these lines to a file, to the Scipyen's console, or execute them again (directly) by double-clicking.</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.dockWidgetHistory.setWindowTitle(QCoreApplication.translate("MainWindow", u"&Command History", None))
#if QT_CONFIG(tooltip)
        self.historyCommandsExecuteToolButton.setToolTip(QCoreApplication.translate("MainWindow", u"Execute selected commands", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.historyCommandsExecuteToolButton.setStatusTip(QCoreApplication.translate("MainWindow", u"Execute selected commands", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.historyCommandsExecuteToolButton.setWhatsThis(QCoreApplication.translate("MainWindow", u"Execute selected commands", None))
#endif // QT_CONFIG(whatsthis)
        self.historyCommandsExecuteToolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.historyCommandsToConsoleToolButton.setToolTip(QCoreApplication.translate("MainWindow", u"Send commands to console", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.historyCommandsToConsoleToolButton.setStatusTip(QCoreApplication.translate("MainWindow", u"Send commands to console", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.historyCommandsToConsoleToolButton.setWhatsThis(QCoreApplication.translate("MainWindow", u"Send commands to console", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.historyCommandsToConsoleToolButton.setAccessibleName(QCoreApplication.translate("MainWindow", u"Send commands to console", None))
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.historyCommandsToConsoleToolButton.setAccessibleDescription(QCoreApplication.translate("MainWindow", u"Send commands to console", None))
#endif // QT_CONFIG(accessibility)
        self.historyCommandsToConsoleToolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.copyHistoryCommands.setToolTip(QCoreApplication.translate("MainWindow", u"Copy selected commands to clipboard", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.copyHistoryCommands.setStatusTip(QCoreApplication.translate("MainWindow", u"Copy selected commands to clipboard", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.copyHistoryCommands.setWhatsThis(QCoreApplication.translate("MainWindow", u"Copy selected commands to clipboard", None))
#endif // QT_CONFIG(whatsthis)
        self.copyHistoryCommands.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.saveHistoryToolbutton.setToolTip(QCoreApplication.translate("MainWindow", u"Save history to file", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.saveHistoryToolbutton.setStatusTip(QCoreApplication.translate("MainWindow", u"Save history to file", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.saveHistoryToolbutton.setWhatsThis(QCoreApplication.translate("MainWindow", u"Save history to file", None))
#endif // QT_CONFIG(whatsthis)
        self.saveHistoryToolbutton.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.commandHistoryFinderComboBox.setToolTip(QCoreApplication.translate("MainWindow", u"Search for commands in the selected session, using regular expressions", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.commandHistoryFinderComboBox.setStatusTip(QCoreApplication.translate("MainWindow", u"Search for commands in the selected session, using regular expressions", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.commandHistoryFinderComboBox.setWhatsThis(QCoreApplication.translate("MainWindow", u"Search for commands in the selected session, using regular expressions", None))
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(tooltip)
        self.dockWidgetFileSystem.setToolTip(QCoreApplication.translate("MainWindow", u"Scipyen's file system navigator", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.dockWidgetFileSystem.setStatusTip(QCoreApplication.translate("MainWindow", u"Scipyen's file system navigator", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.dockWidgetFileSystem.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Scipyen's file system navigator. </p><p>For access to archive files, including archiving/extracting etc, please use the desktop's own file manager.<br/></p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.dockWidgetFileSystem.setWindowTitle(QCoreApplication.translate("MainWindow", u"File S&ystem", None))
#if QT_CONFIG(tooltip)
        self.dirHomeBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Go to Home directory", None))
#endif // QT_CONFIG(tooltip)
        self.dirHomeBtn.setText(QCoreApplication.translate("MainWindow", u"Home", None))
#if QT_CONFIG(tooltip)
        self.dirBackBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Go back", None))
#endif // QT_CONFIG(tooltip)
        self.dirBackBtn.setText(QCoreApplication.translate("MainWindow", u"Previous directory", None))
#if QT_CONFIG(tooltip)
        self.dirFwdBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Go forward", None))
#endif // QT_CONFIG(tooltip)
        self.dirFwdBtn.setText(QCoreApplication.translate("MainWindow", u"Next directory", None))
#if QT_CONFIG(tooltip)
        self.dirUpBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Go to parent directory", None))
#endif // QT_CONFIG(tooltip)
        self.dirUpBtn.setText(QCoreApplication.translate("MainWindow", u"Parent directory", None))
#if QT_CONFIG(tooltip)
        self.selDirBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Select working directory or click on down arrow for recent directories", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.selDirBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Select working directory or click on down arrow for recent directories", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.selDirBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Select working directory", None))
#endif // QT_CONFIG(whatsthis)
        self.selDirBtn.setText(QCoreApplication.translate("MainWindow", u"&Select Working directory", None))
#if QT_CONFIG(tooltip)
        self.systemOpenFolderBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Open current folder in the system file manager", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.systemOpenFolderBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Open current folder in the system file manager", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.systemOpenFolderBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Open current folder in system file manager", None))
#endif // QT_CONFIG(whatsthis)
        self.systemOpenFolderBtn.setText(QCoreApplication.translate("MainWindow", u"Open File Manager", None))
#if QT_CONFIG(tooltip)
        self.systemOpenParentFolderBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Opens parent of working directory in the system file manager", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.systemOpenParentFolderBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Opens parent directory of working directory in the system file manager", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.systemOpenParentFolderBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Opens parent directory of working directory in system file manager", None))
#endif // QT_CONFIG(whatsthis)
        self.systemOpenParentFolderBtn.setText(QCoreApplication.translate("MainWindow", u"Open Parent Folder in File Manager", None))
#if QT_CONFIG(tooltip)
        self.openTermBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Open system terminal in current folder", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.openTermBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Open system terminal in current folder", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.openTermBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Open system terminal in current folder", None))
#endif // QT_CONFIG(whatsthis)
        self.openTermBtn.setText(QCoreApplication.translate("MainWindow", u"Open System Terminal", None))
#if QT_CONFIG(tooltip)
        self.fileSystemViewToolButton.setToolTip(QCoreApplication.translate("MainWindow", u"Change File System View", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.fileSystemViewToolButton.setStatusTip(QCoreApplication.translate("MainWindow", u"Change File System View", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.fileSystemViewToolButton.setWhatsThis(QCoreApplication.translate("MainWindow", u"Change File System View", None))
#endif // QT_CONFIG(whatsthis)
        self.fileSystemViewToolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.toggleFilesFilterToolBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle filter bar", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.toggleFilesFilterToolBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Toggle filter bar", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.toggleFilesFilterToolBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Toggle filter bar - to filter files by name", None))
#endif // QT_CONFIG(whatsthis)
        self.toggleFilesFilterToolBtn.setText(QCoreApplication.translate("MainWindow", u"Filter...", None))
        self.filesFilterLabel.setText(QCoreApplication.translate("MainWindow", u"Filter:", None))
#if QT_CONFIG(tooltip)
        self.fileSystemFilter.setToolTip(QCoreApplication.translate("MainWindow", u"Filter files by name and/or extension, using regular expressions", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.fileSystemFilter.setStatusTip(QCoreApplication.translate("MainWindow", u"Filter files by name and/or extension, using regular expressions", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.fileSystemFilter.setWhatsThis(QCoreApplication.translate("MainWindow", u"Filter files by name and/or extension, using regular expressions", None))
#endif // QT_CONFIG(whatsthis)
        self.fileSystemFilter.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter file name filter", None))
#if QT_CONFIG(tooltip)
        self.hideFilteredOutnamesToolButton.setToolTip(QCoreApplication.translate("MainWindow", u"Hide non-matching file names", None))
#endif // QT_CONFIG(tooltip)
        self.hideFilteredOutnamesToolButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.hideFilesFilterToolBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Hide file filter", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.hideFilesFilterToolBtn.setStatusTip(QCoreApplication.translate("MainWindow", u"Hide file filter", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.hideFilesFilterToolBtn.setWhatsThis(QCoreApplication.translate("MainWindow", u"Hide file filter", None))
#endif // QT_CONFIG(whatsthis)
        self.hideFilesFilterToolBtn.setText(QCoreApplication.translate("MainWindow", u"Hide", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"ScipyenMainToolBar", None))
#if QT_CONFIG(tooltip)
        self.toolBar.setToolTip(QCoreApplication.translate("MainWindow", u"Save variables to HDF5 file", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.toolBar.setStatusTip(QCoreApplication.translate("MainWindow", u"Save selected variables for HDF5 (*.h5) files", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.toolBar.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>When a single variable is selected in the workspace (User Variables tab), shows a file save dialog to choose among supported file types. </p><p><br/></p><p>When more than one variable is selected, saves all of them to HDF5 files named after the variable name (symbol) in the workspace.</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
    # retranslateUi

