from .resources import breeze_dark_rc
from .resources import breeze_dark_16x16_rc
from .resources import breeze_dark_22x22_rc
from .resources import breeze_dark_8x8_rc
from .resources import breeze_dark_actions_rc
from .resources import breeze_dark_animations_rc
from .resources import breeze_dark_applets_rc
from .resources import breeze_dark_apps_rc
from .resources import breeze_dark_categories_rc
from .resources import breeze_dark_devices_rc
from .resources import breeze_dark_emblems_rc
from .resources import breeze_dark_emotes_rc
from .resources import breeze_dark_mimetypes_rc
from .resources import breeze_dark_places_rc
from .resources import breeze_dark_preferences_rc
from .resources import breeze_dark_status_rc
from .resources import breeze_rc
from .resources import breeze_16x16_rc
from .resources import breeze_22x22_rc
from .resources import breeze_actions_rc
from .resources import breeze_animations_rc
from .resources import breeze_applets_rc
from .resources import breeze_apps_rc
from .resources import breeze_categories_rc
from .resources import breeze_devices_rc
from .resources import breeze_emblems_rc
from .resources import breeze_emotes_rc
from .resources import breeze_mimetypes_rc
from .resources import breeze_places_rc
from .resources import breeze_preferences_rc
from .resources import breeze_status_rc
from . import images_rc
