# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'signalviewer.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDockWidget,
    QGridLayout, QHBoxLayout, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QSizePolicy, QSpacerItem,
    QStatusBar, QToolBar, QVBoxLayout, QWidget)

from gui.widgets.datatreeview import DataTreeView
from gui.widgets.spinboxslider import SpinBoxSlider

class Ui_SignalViewerWindow(object):
    def setupUi(self, SignalViewerWindow):
        if not SignalViewerWindow.objectName():
            SignalViewerWindow.setObjectName(u"SignalViewerWindow")
        SignalViewerWindow.resize(827, 435)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SignalViewerWindow.sizePolicy().hasHeightForWidth())
        SignalViewerWindow.setSizePolicy(sizePolicy)
        self.actionClose = QAction(SignalViewerWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionColorMap = QAction(SignalViewerWindow)
        self.actionColorMap.setObjectName(u"actionColorMap")
        self.actionImageScale = QAction(SignalViewerWindow)
        self.actionImageScale.setObjectName(u"actionImageScale")
        self.actionImageGamma = QAction(SignalViewerWindow)
        self.actionImageGamma.setObjectName(u"actionImageGamma")
        self.actionOpen = QAction(SignalViewerWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionCrosshair_Cursor = QAction(SignalViewerWindow)
        self.actionCrosshair_Cursor.setObjectName(u"actionCrosshair_Cursor")
        icon = QIcon(QIcon.fromTheme(u"escape-direction-all"))
        self.actionCrosshair_Cursor.setIcon(icon)
        self.actionVertical_Cursor = QAction(SignalViewerWindow)
        self.actionVertical_Cursor.setObjectName(u"actionVertical_Cursor")
        icon1 = QIcon(QIcon.fromTheme(u"escape-direction-vertical"))
        self.actionVertical_Cursor.setIcon(icon1)
        self.actionHorizontal_Cursor = QAction(SignalViewerWindow)
        self.actionHorizontal_Cursor.setObjectName(u"actionHorizontal_Cursor")
        icon2 = QIcon(QIcon.fromTheme(u"escape-direction-horizontal"))
        self.actionHorizontal_Cursor.setIcon(icon2)
        self.actionRemove_Cursor = QAction(SignalViewerWindow)
        self.actionRemove_Cursor.setObjectName(u"actionRemove_Cursor")
        icon3 = QIcon(QIcon.fromTheme(u"remove"))
        self.actionRemove_Cursor.setIcon(icon3)
        self.actionSVG = QAction(SignalViewerWindow)
        self.actionSVG.setObjectName(u"actionSVG")
        self.actionTIFF = QAction(SignalViewerWindow)
        self.actionTIFF.setObjectName(u"actionTIFF")
        self.actionPNG = QAction(SignalViewerWindow)
        self.actionPNG.setObjectName(u"actionPNG")
        self.actionDetect_Triggers = QAction(SignalViewerWindow)
        self.actionDetect_Triggers.setObjectName(u"actionDetect_Triggers")
        self.actionDetect_Triggers.setEnabled(False)
        icon4 = QIcon(QIcon.fromTheme(u"mark-location"))
        self.actionDetect_Triggers.setIcon(icon4)
        self.actionRefresh = QAction(SignalViewerWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        icon5 = QIcon(QIcon.fromTheme(u"view-refresh"))
        self.actionRefresh.setIcon(icon5)
        self.actionData_to_workspace = QAction(SignalViewerWindow)
        self.actionData_to_workspace.setObjectName(u"actionData_to_workspace")
        self.actionShow_Legends = QAction(SignalViewerWindow)
        self.actionShow_Legends.setObjectName(u"actionShow_Legends")
        self.actionShow_Legends.setCheckable(True)
        self.actionIgnore_empty_spike_trains = QAction(SignalViewerWindow)
        self.actionIgnore_empty_spike_trains.setObjectName(u"actionIgnore_empty_spike_trains")
        self.actionIgnore_empty_spike_trains.setCheckable(True)
        self.setCursorsShowValue = QAction(SignalViewerWindow)
        self.setCursorsShowValue.setObjectName(u"setCursorsShowValue")
        self.setCursorsShowValue.setCheckable(True)
        self.setCursorsShowValue.setChecked(False)
        icon6 = QIcon(QIcon.fromTheme(u"draw-number"))
        self.setCursorsShowValue.setIcon(icon6)
        self.setCursorsLabelPrecisionAction = QAction(SignalViewerWindow)
        self.setCursorsLabelPrecisionAction.setObjectName(u"setCursorsLabelPrecisionAction")
        icon7 = QIcon(QIcon.fromTheme(u"format-precision-more"))
        self.setCursorsLabelPrecisionAction.setIcon(icon7)
        self.addVerticalCursorAction = QAction(SignalViewerWindow)
        self.addVerticalCursorAction.setObjectName(u"addVerticalCursorAction")
        self.addHorizontalCursorAction = QAction(SignalViewerWindow)
        self.addHorizontalCursorAction.setObjectName(u"addHorizontalCursorAction")
        self.addMultiAxisVCursorAction = QAction(SignalViewerWindow)
        self.addMultiAxisVCursorAction.setObjectName(u"addMultiAxisVCursorAction")
        self.addMultiAxisCCursorAction = QAction(SignalViewerWindow)
        self.addMultiAxisCCursorAction.setObjectName(u"addMultiAxisCCursorAction")
        self.addDynamicMultiAxisVCursorAction = QAction(SignalViewerWindow)
        self.addDynamicMultiAxisVCursorAction.setObjectName(u"addDynamicMultiAxisVCursorAction")
        self.addDynamicMultiAxisCCursorAction = QAction(SignalViewerWindow)
        self.addDynamicMultiAxisCCursorAction.setObjectName(u"addDynamicMultiAxisCCursorAction")
        self.addCrosshairCursorAction = QAction(SignalViewerWindow)
        self.addCrosshairCursorAction.setObjectName(u"addCrosshairCursorAction")
        self.addDynamicVerticalCursorAction = QAction(SignalViewerWindow)
        self.addDynamicVerticalCursorAction.setObjectName(u"addDynamicVerticalCursorAction")
        self.addDynamicHorizontalCursorAction = QAction(SignalViewerWindow)
        self.addDynamicHorizontalCursorAction.setObjectName(u"addDynamicHorizontalCursorAction")
        self.addDynamicCrosshairCursorAction = QAction(SignalViewerWindow)
        self.addDynamicCrosshairCursorAction.setObjectName(u"addDynamicCrosshairCursorAction")
        self.editAnyCursorAction = QAction(SignalViewerWindow)
        self.editAnyCursorAction.setObjectName(u"editAnyCursorAction")
        self.editCursorAction = QAction(SignalViewerWindow)
        self.editCursorAction.setObjectName(u"editCursorAction")
        self.removeCursorAction = QAction(SignalViewerWindow)
        self.removeCursorAction.setObjectName(u"removeCursorAction")
        self.removeSelectedCursorAction = QAction(SignalViewerWindow)
        self.removeSelectedCursorAction.setObjectName(u"removeSelectedCursorAction")
        self.removeAllCursorsAction = QAction(SignalViewerWindow)
        self.removeAllCursorsAction.setObjectName(u"removeAllCursorsAction")
        self.verticalCursorColorsAction = QAction(SignalViewerWindow)
        self.verticalCursorColorsAction.setObjectName(u"verticalCursorColorsAction")
        self.horizontalCursorColorsAction = QAction(SignalViewerWindow)
        self.horizontalCursorColorsAction.setObjectName(u"horizontalCursorColorsAction")
        self.crosshairCursorColorsAction = QAction(SignalViewerWindow)
        self.crosshairCursorColorsAction.setObjectName(u"crosshairCursorColorsAction")
        self.cursorHoverColorAction = QAction(SignalViewerWindow)
        self.cursorHoverColorAction.setObjectName(u"cursorHoverColorAction")
        self.epochsFromCursorsAction = QAction(SignalViewerWindow)
        self.epochsFromCursorsAction.setObjectName(u"epochsFromCursorsAction")
        icon8 = QIcon(QIcon.fromTheme(u"timeline-use-zone-on"))
        self.epochsFromCursorsAction.setIcon(icon8)
        self.epochFromSelectedCursorAction = QAction(SignalViewerWindow)
        self.epochFromSelectedCursorAction.setObjectName(u"epochFromSelectedCursorAction")
        self.epochFromSelectedCursorAction.setIcon(icon8)
        self.epochBetweenCursorsAction = QAction(SignalViewerWindow)
        self.epochBetweenCursorsAction.setObjectName(u"epochBetweenCursorsAction")
        self.epochBetweenCursorsAction.setIcon(icon8)
        self.epochsInDataFromCursorsAction = QAction(SignalViewerWindow)
        self.epochsInDataFromCursorsAction.setObjectName(u"epochsInDataFromCursorsAction")
        icon9 = QIcon(QIcon.fromTheme(u"preview-add-zone"))
        self.epochsInDataFromCursorsAction.setIcon(icon9)
        self.epochInDataFromSelectedCursorAction = QAction(SignalViewerWindow)
        self.epochInDataFromSelectedCursorAction.setObjectName(u"epochInDataFromSelectedCursorAction")
        self.epochInDataFromSelectedCursorAction.setIcon(icon9)
        self.epochInDataBetweenCursors = QAction(SignalViewerWindow)
        self.epochInDataBetweenCursors.setObjectName(u"epochInDataBetweenCursors")
        self.epochInDataBetweenCursors.setIcon(icon9)
        self.actionLink_X_axes = QAction(SignalViewerWindow)
        self.actionLink_X_axes.setObjectName(u"actionLink_X_axes")
        self.actionLink_X_axes.setCheckable(True)
        icon10 = QIcon(QIcon.fromTheme(u"link"))
        self.actionLink_X_axes.setIcon(icon10)
        self.actionUnlink_X_Axes = QAction(SignalViewerWindow)
        self.actionUnlink_X_Axes.setObjectName(u"actionUnlink_X_Axes")
        icon11 = QIcon(QIcon.fromTheme(u"remove-link"))
        self.actionUnlink_X_Axes.setIcon(icon11)
        self.actionShow_Cursor_Edit_Dialog_When_Created = QAction(SignalViewerWindow)
        self.actionShow_Cursor_Edit_Dialog_When_Created.setObjectName(u"actionShow_Cursor_Edit_Dialog_When_Created")
        self.actionShow_Cursor_Edit_Dialog_When_Created.setCheckable(True)
        icon12 = QIcon(QIcon.fromTheme(u"settings-configure"))
        self.actionShow_Cursor_Edit_Dialog_When_Created.setIcon(icon12)
        self.actionVerticalCursorsFromEpochInCurrentAxis = QAction(SignalViewerWindow)
        self.actionVerticalCursorsFromEpochInCurrentAxis.setObjectName(u"actionVerticalCursorsFromEpochInCurrentAxis")
        icon13 = QIcon(QIcon.fromTheme(u"zone-out"))
        self.actionVerticalCursorsFromEpochInCurrentAxis.setIcon(icon13)
        self.actionMultiAxisVerticalCursorsFromEpoch = QAction(SignalViewerWindow)
        self.actionMultiAxisVerticalCursorsFromEpoch.setObjectName(u"actionMultiAxisVerticalCursorsFromEpoch")
        self.actionMultiAxisVerticalCursorsFromEpoch.setEnabled(True)
        self.actionShow_X_grid = QAction(SignalViewerWindow)
        self.actionShow_X_grid.setObjectName(u"actionShow_X_grid")
        self.actionShow_X_grid.setCheckable(True)
        icon14 = QIcon(QIcon.fromTheme(u"labplot-axis-horizontal"))
        self.actionShow_X_grid.setIcon(icon14)
        self.actionShow_Y_grid = QAction(SignalViewerWindow)
        self.actionShow_Y_grid.setObjectName(u"actionShow_Y_grid")
        self.actionShow_Y_grid.setCheckable(True)
        icon15 = QIcon(QIcon.fromTheme(u"labplot-axis-vertical"))
        self.actionShow_Y_grid.setIcon(icon15)
        self.actionViewMain_Toolbar = QAction(SignalViewerWindow)
        self.actionViewMain_Toolbar.setObjectName(u"actionViewMain_Toolbar")
        self.actionViewMain_Toolbar.setCheckable(True)
        self.actionViewMain_Toolbar.setChecked(True)
        self.actionViewFrame_Navigator = QAction(SignalViewerWindow)
        self.actionViewFrame_Navigator.setObjectName(u"actionViewFrame_Navigator")
        self.actionViewFrame_Navigator.setCheckable(True)
        self.actionViewFrame_Navigator.setChecked(True)
        self.actionViewSignal_Selectors = QAction(SignalViewerWindow)
        self.actionViewSignal_Selectors.setObjectName(u"actionViewSignal_Selectors")
        self.actionViewSignal_Selectors.setCheckable(True)
        self.actionViewSignal_Selectors.setChecked(True)
        self.actionVertical_cursor_series = QAction(SignalViewerWindow)
        self.actionVertical_cursor_series.setObjectName(u"actionVertical_cursor_series")
        self.actionLeft_Axis_Spacer = QAction(SignalViewerWindow)
        self.actionLeft_Axis_Spacer.setObjectName(u"actionLeft_Axis_Spacer")
        icon16 = QIcon(QIcon.fromTheme(u"adjustcol"))
        self.actionLeft_Axis_Spacer.setIcon(icon16)
        self.actionExportVerticalCursorData = QAction(SignalViewerWindow)
        self.actionExportVerticalCursorData.setObjectName(u"actionExportVerticalCursorData")
        self.actionExportHorizontalCursorData = QAction(SignalViewerWindow)
        self.actionExportHorizontalCursorData.setObjectName(u"actionExportHorizontalCursorData")
        self.actionExportCrosshairCursorData = QAction(SignalViewerWindow)
        self.actionExportCrosshairCursorData.setObjectName(u"actionExportCrosshairCursorData")
        self.actionViewCursors_Toolbar = QAction(SignalViewerWindow)
        self.actionViewCursors_Toolbar.setObjectName(u"actionViewCursors_Toolbar")
        self.actionViewCursors_Toolbar.setCheckable(True)
        self.actionViewTriggers_Toolbar = QAction(SignalViewerWindow)
        self.actionViewTriggers_Toolbar.setObjectName(u"actionViewTriggers_Toolbar")
        self.actionViewTriggers_Toolbar.setCheckable(True)
        self.actionLockToolbars = QAction(SignalViewerWindow)
        self.actionLockToolbars.setObjectName(u"actionLockToolbars")
        self.actionLockToolbars.setCheckable(True)
        icon17 = QIcon(QIcon.fromTheme(u"object-locked"))
        self.actionLockToolbars.setIcon(icon17)
        self.actionRemoveTriggers = QAction(SignalViewerWindow)
        self.actionRemoveTriggers.setObjectName(u"actionRemoveTriggers")
        self.actionRemoveTriggers.setIcon(icon3)
        self.actionRemoveAllEvents = QAction(SignalViewerWindow)
        self.actionRemoveAllEvents.setObjectName(u"actionRemoveAllEvents")
        icon18 = QIcon(QIcon.fromTheme(u"delete"))
        self.actionRemoveAllEvents.setIcon(icon18)
        self.actionViewEpochs_Toolbar = QAction(SignalViewerWindow)
        self.actionViewEpochs_Toolbar.setObjectName(u"actionViewEpochs_Toolbar")
        self.actionViewEpochs_Toolbar.setCheckable(True)
        self.actionRemove_All_Epochs = QAction(SignalViewerWindow)
        self.actionRemove_All_Epochs.setObjectName(u"actionRemove_All_Epochs")
        icon19 = QIcon(QIcon.fromTheme(u"preview-remove-zone"))
        self.actionRemove_All_Epochs.setIcon(icon19)
        self.actionEnable_Auto_Range = QAction(SignalViewerWindow)
        self.actionEnable_Auto_Range.setObjectName(u"actionEnable_Auto_Range")
        self.actionEnable_Auto_Range.setCheckable(True)
        icon20 = QIcon(QIcon.fromTheme(u"auto-scale-all"))
        self.actionEnable_Auto_Range.setIcon(icon20)
        self.actionAutoScaleSelectedAxis = QAction(SignalViewerWindow)
        self.actionAutoScaleSelectedAxis.setObjectName(u"actionAutoScaleSelectedAxis")
        self.actionAutoScaleSelectedAxis.setIcon(icon20)
        self.actionAutoScaleSelectedAxis.setMenuRole(QAction.MenuRole.NoRole)
        self.actionRemove_All_Cursors = QAction(SignalViewerWindow)
        self.actionRemove_All_Cursors.setObjectName(u"actionRemove_All_Cursors")
        self.actionRemove_All_Cursors.setIcon(icon18)
        self.centralwidget = QWidget(SignalViewerWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.viewerWidgetContainer = QWidget(self.centralwidget)
        self.viewerWidgetContainer.setObjectName(u"viewerWidgetContainer")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(10)
        sizePolicy1.setVerticalStretch(10)
        sizePolicy1.setHeightForWidth(self.viewerWidgetContainer.sizePolicy().hasHeightForWidth())
        self.viewerWidgetContainer.setSizePolicy(sizePolicy1)

        self.verticalLayout.addWidget(self.viewerWidgetContainer)

        self.selectorsWidget = QWidget(self.centralwidget)
        self.selectorsWidget.setObjectName(u"selectorsWidget")
        self.gridLayout = QGridLayout(self.selectorsWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.selectorsLayout = QHBoxLayout()
        self.selectorsLayout.setObjectName(u"selectorsLayout")
        self.plotAnalogSignalsCheckBox = QCheckBox(self.selectorsWidget)
        self.plotAnalogSignalsCheckBox.setObjectName(u"plotAnalogSignalsCheckBox")
        self.plotAnalogSignalsCheckBox.setChecked(True)

        self.selectorsLayout.addWidget(self.plotAnalogSignalsCheckBox)

        self.analogSignalComboBox = QComboBox(self.selectorsWidget)
        self.analogSignalComboBox.setObjectName(u"analogSignalComboBox")

        self.selectorsLayout.addWidget(self.analogSignalComboBox)

        self.plotIrregularSignalsCheckBox = QCheckBox(self.selectorsWidget)
        self.plotIrregularSignalsCheckBox.setObjectName(u"plotIrregularSignalsCheckBox")
        self.plotIrregularSignalsCheckBox.setChecked(True)

        self.selectorsLayout.addWidget(self.plotIrregularSignalsCheckBox)

        self.irregularSignalComboBox = QComboBox(self.selectorsWidget)
        self.irregularSignalComboBox.setObjectName(u"irregularSignalComboBox")

        self.selectorsLayout.addWidget(self.irregularSignalComboBox)

        self.plotSpikeTrainsCheckBox = QCheckBox(self.selectorsWidget)
        self.plotSpikeTrainsCheckBox.setObjectName(u"plotSpikeTrainsCheckBox")
        self.plotSpikeTrainsCheckBox.setChecked(True)

        self.selectorsLayout.addWidget(self.plotSpikeTrainsCheckBox)

        self.plotEventsCheckBox = QCheckBox(self.selectorsWidget)
        self.plotEventsCheckBox.setObjectName(u"plotEventsCheckBox")
        self.plotEventsCheckBox.setChecked(True)

        self.selectorsLayout.addWidget(self.plotEventsCheckBox)

        self.plotEpochsCheckBox = QCheckBox(self.selectorsWidget)
        self.plotEpochsCheckBox.setObjectName(u"plotEpochsCheckBox")
        self.plotEpochsCheckBox.setChecked(True)

        self.selectorsLayout.addWidget(self.plotEpochsCheckBox)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.selectorsLayout.addItem(self.horizontalSpacer)


        self.gridLayout.addLayout(self.selectorsLayout, 0, 0, 1, 1)


        self.verticalLayout.addWidget(self.selectorsWidget)

        self._frames_spinBoxSlider_ = SpinBoxSlider(self.centralwidget)
        self._frames_spinBoxSlider_.setObjectName(u"_frames_spinBoxSlider_")

        self.verticalLayout.addWidget(self._frames_spinBoxSlider_)

        SignalViewerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(SignalViewerWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 827, 27))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuExport = QMenu(self.menuFile)
        self.menuExport.setObjectName(u"menuExport")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuTriggers = QMenu(self.menuTools)
        self.menuTriggers.setObjectName(u"menuTriggers")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuView = QMenu(self.menuSettings)
        self.menuView.setObjectName(u"menuView")
        self.menuAxes = QMenu(self.menuSettings)
        self.menuAxes.setObjectName(u"menuAxes")
        self.cursorsMenu = QMenu(self.menubar)
        self.cursorsMenu.setObjectName(u"cursorsMenu")
        self.addCursorsMenu = QMenu(self.cursorsMenu)
        self.addCursorsMenu.setObjectName(u"addCursorsMenu")
        self.addMultiAxesCursorMenu = QMenu(self.addCursorsMenu)
        self.addMultiAxesCursorMenu.setObjectName(u"addMultiAxesCursorMenu")
        self.editCursorsMenu = QMenu(self.cursorsMenu)
        self.editCursorsMenu.setObjectName(u"editCursorsMenu")
        self.removeCursorsMenu = QMenu(self.cursorsMenu)
        self.removeCursorsMenu.setObjectName(u"removeCursorsMenu")
        self.cursorsColorsMenu = QMenu(self.cursorsMenu)
        self.cursorsColorsMenu.setObjectName(u"cursorsColorsMenu")
        self.menuVerticalCursorsFromEpoch = QMenu(self.cursorsMenu)
        self.menuVerticalCursorsFromEpoch.setObjectName(u"menuVerticalCursorsFromEpoch")
        self.menuVerticalCursorsFromEpoch.setToolTipsVisible(True)
        self.menuExport_Cursor_Data = QMenu(self.cursorsMenu)
        self.menuExport_Cursor_Data.setObjectName(u"menuExport_Cursor_Data")
        self.epochsMenu = QMenu(self.menubar)
        self.epochsMenu.setObjectName(u"epochsMenu")
        self.makeEpochsMenu = QMenu(self.epochsMenu)
        self.makeEpochsMenu.setObjectName(u"makeEpochsMenu")
        self.makeEpochsMenu.setIcon(icon8)
        self.makeEpochsInDataMenu = QMenu(self.epochsMenu)
        self.makeEpochsInDataMenu.setObjectName(u"makeEpochsInDataMenu")
        self.makeEpochsInDataMenu.setIcon(icon9)
        SignalViewerWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(SignalViewerWindow)
        self.statusbar.setObjectName(u"statusbar")
        SignalViewerWindow.setStatusBar(self.statusbar)
        self.cursorsDockWidget = QDockWidget(SignalViewerWindow)
        self.cursorsDockWidget.setObjectName(u"cursorsDockWidget")
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout_2 = QGridLayout(self.dockWidgetContents)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.coordinatesViewer = QPlainTextEdit(self.dockWidgetContents)
        self.coordinatesViewer.setObjectName(u"coordinatesViewer")
        self.coordinatesViewer.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByKeyboard|Qt.TextInteractionFlag.TextSelectableByMouse)

        self.gridLayout_2.addWidget(self.coordinatesViewer, 0, 0, 1, 1)

        self.cursorsDockWidget.setWidget(self.dockWidgetContents)
        SignalViewerWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.cursorsDockWidget)
        self.annotationsDockWidget = QDockWidget(SignalViewerWindow)
        self.annotationsDockWidget.setObjectName(u"annotationsDockWidget")
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.gridLayout_3 = QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.annotationsViewer = DataTreeView(self.dockWidgetContents_2)
        self.annotationsViewer.setObjectName(u"annotationsViewer")

        self.gridLayout_3.addWidget(self.annotationsViewer, 0, 0, 1, 1)

        self.annotationsDockWidget.setWidget(self.dockWidgetContents_2)
        SignalViewerWindow.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.annotationsDockWidget)
        self.mainToolBar = QToolBar(SignalViewerWindow)
        self.mainToolBar.setObjectName(u"mainToolBar")
        SignalViewerWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.mainToolBar)
        self.cursorsToolBar = QToolBar(SignalViewerWindow)
        self.cursorsToolBar.setObjectName(u"cursorsToolBar")
        SignalViewerWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.cursorsToolBar)
        self.triggersToolBar = QToolBar(SignalViewerWindow)
        self.triggersToolBar.setObjectName(u"triggersToolBar")
        SignalViewerWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.triggersToolBar)
        self.epochsToolBar = QToolBar(SignalViewerWindow)
        self.epochsToolBar.setObjectName(u"epochsToolBar")
        SignalViewerWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.epochsToolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.cursorsMenu.menuAction())
        self.menubar.addAction(self.epochsMenu.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionRefresh)
        self.menuExport.addAction(self.actionSVG)
        self.menuExport.addAction(self.actionTIFF)
        self.menuExport.addAction(self.actionPNG)
        self.menuExport.addAction(self.actionData_to_workspace)
        self.menuTools.addAction(self.menuTriggers.menuAction())
        self.menuTriggers.addAction(self.actionDetect_Triggers)
        self.menuTriggers.addAction(self.actionRemoveTriggers)
        self.menuSettings.addAction(self.actionShow_Legends)
        self.menuSettings.addAction(self.actionIgnore_empty_spike_trains)
        self.menuSettings.addAction(self.actionShow_Cursor_Edit_Dialog_When_Created)
        self.menuSettings.addAction(self.setCursorsShowValue)
        self.menuSettings.addAction(self.menuView.menuAction())
        self.menuSettings.addAction(self.menuAxes.menuAction())
        self.menuView.addAction(self.actionViewMain_Toolbar)
        self.menuView.addAction(self.actionViewFrame_Navigator)
        self.menuView.addAction(self.actionViewSignal_Selectors)
        self.menuView.addAction(self.actionViewCursors_Toolbar)
        self.menuView.addAction(self.actionViewEpochs_Toolbar)
        self.menuView.addAction(self.actionViewTriggers_Toolbar)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionLockToolbars)
        self.menuAxes.addAction(self.actionLink_X_axes)
        self.menuAxes.addAction(self.actionShow_X_grid)
        self.menuAxes.addAction(self.actionShow_Y_grid)
        self.menuAxes.addAction(self.actionLeft_Axis_Spacer)
        self.menuAxes.addAction(self.actionEnable_Auto_Range)
        self.cursorsMenu.addAction(self.addCursorsMenu.menuAction())
        self.cursorsMenu.addAction(self.editCursorsMenu.menuAction())
        self.cursorsMenu.addAction(self.removeCursorsMenu.menuAction())
        self.cursorsMenu.addAction(self.menuVerticalCursorsFromEpoch.menuAction())
        self.cursorsMenu.addAction(self.menuExport_Cursor_Data.menuAction())
        self.cursorsMenu.addSeparator()
        self.cursorsMenu.addAction(self.setCursorsShowValue)
        self.cursorsMenu.addAction(self.setCursorsLabelPrecisionAction)
        self.cursorsMenu.addAction(self.cursorsColorsMenu.menuAction())
        self.addCursorsMenu.addAction(self.addVerticalCursorAction)
        self.addCursorsMenu.addAction(self.addHorizontalCursorAction)
        self.addCursorsMenu.addAction(self.addCrosshairCursorAction)
        self.addCursorsMenu.addAction(self.addMultiAxesCursorMenu.menuAction())
        self.addCursorsMenu.addSeparator()
        self.addCursorsMenu.addAction(self.addDynamicVerticalCursorAction)
        self.addCursorsMenu.addAction(self.addDynamicHorizontalCursorAction)
        self.addCursorsMenu.addAction(self.addDynamicCrosshairCursorAction)
        self.addCursorsMenu.addSeparator()
        self.addCursorsMenu.addAction(self.actionVertical_cursor_series)
        self.addMultiAxesCursorMenu.addAction(self.addMultiAxisVCursorAction)
        self.addMultiAxesCursorMenu.addAction(self.addMultiAxisCCursorAction)
        self.addMultiAxesCursorMenu.addSeparator()
        self.addMultiAxesCursorMenu.addAction(self.addDynamicMultiAxisVCursorAction)
        self.addMultiAxesCursorMenu.addAction(self.addDynamicMultiAxisCCursorAction)
        self.editCursorsMenu.addAction(self.editAnyCursorAction)
        self.editCursorsMenu.addAction(self.editCursorAction)
        self.removeCursorsMenu.addAction(self.removeCursorAction)
        self.removeCursorsMenu.addAction(self.removeSelectedCursorAction)
        self.removeCursorsMenu.addAction(self.removeAllCursorsAction)
        self.cursorsColorsMenu.addAction(self.verticalCursorColorsAction)
        self.cursorsColorsMenu.addAction(self.horizontalCursorColorsAction)
        self.cursorsColorsMenu.addAction(self.crosshairCursorColorsAction)
        self.cursorsColorsMenu.addAction(self.cursorHoverColorAction)
        self.menuVerticalCursorsFromEpoch.addAction(self.actionVerticalCursorsFromEpochInCurrentAxis)
        self.menuVerticalCursorsFromEpoch.addAction(self.actionMultiAxisVerticalCursorsFromEpoch)
        self.menuExport_Cursor_Data.addAction(self.actionExportVerticalCursorData)
        self.menuExport_Cursor_Data.addAction(self.actionExportHorizontalCursorData)
        self.menuExport_Cursor_Data.addAction(self.actionExportCrosshairCursorData)
        self.epochsMenu.addAction(self.makeEpochsInDataMenu.menuAction())
        self.epochsMenu.addAction(self.makeEpochsMenu.menuAction())
        self.epochsMenu.addAction(self.actionRemove_All_Epochs)
        self.makeEpochsMenu.addAction(self.epochsFromCursorsAction)
        self.makeEpochsMenu.addAction(self.epochFromSelectedCursorAction)
        self.makeEpochsMenu.addAction(self.epochBetweenCursorsAction)
        self.makeEpochsInDataMenu.addAction(self.epochsInDataFromCursorsAction)
        self.makeEpochsInDataMenu.addAction(self.epochInDataFromSelectedCursorAction)
        self.makeEpochsInDataMenu.addAction(self.epochInDataBetweenCursors)
        self.mainToolBar.addAction(self.actionRefresh)
        self.mainToolBar.addAction(self.actionLink_X_axes)
        self.mainToolBar.addAction(self.actionAutoScaleSelectedAxis)
        self.mainToolBar.addAction(self.actionShow_X_grid)
        self.mainToolBar.addAction(self.actionShow_Y_grid)
        self.cursorsToolBar.addAction(self.actionVertical_Cursor)
        self.cursorsToolBar.addAction(self.actionCrosshair_Cursor)
        self.cursorsToolBar.addAction(self.actionHorizontal_Cursor)
        self.cursorsToolBar.addAction(self.actionRemove_Cursor)
        self.cursorsToolBar.addAction(self.actionRemove_All_Cursors)
        self.triggersToolBar.addAction(self.actionDetect_Triggers)
        self.triggersToolBar.addAction(self.actionRemoveTriggers)
        self.triggersToolBar.addAction(self.actionRemoveAllEvents)
        self.epochsToolBar.addAction(self.epochsInDataFromCursorsAction)
        self.epochsToolBar.addAction(self.epochInDataFromSelectedCursorAction)
        self.epochsToolBar.addAction(self.epochInDataBetweenCursors)
        self.epochsToolBar.addAction(self.actionRemove_All_Epochs)

        self.retranslateUi(SignalViewerWindow)
        self.actionClose.triggered.connect(SignalViewerWindow.close)

        QMetaObject.connectSlotsByName(SignalViewerWindow)
    # setupUi

    def retranslateUi(self, SignalViewerWindow):
        SignalViewerWindow.setWindowTitle(QCoreApplication.translate("SignalViewerWindow", u"Signal Viewer", None))
        self.actionClose.setText(QCoreApplication.translate("SignalViewerWindow", u"&Close", None))
        self.actionColorMap.setText(QCoreApplication.translate("SignalViewerWindow", u"&Color Map", None))
        self.actionImageScale.setText(QCoreApplication.translate("SignalViewerWindow", u"&Image Scale", None))
        self.actionImageGamma.setText(QCoreApplication.translate("SignalViewerWindow", u"Image &Gamma", None))
        self.actionOpen.setText(QCoreApplication.translate("SignalViewerWindow", u"&Open", None))
        self.actionCrosshair_Cursor.setText(QCoreApplication.translate("SignalViewerWindow", u"Crosshair", None))
#if QT_CONFIG(tooltip)
        self.actionCrosshair_Cursor.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Add a crosshair cursor to current axis;</p><p>press &amp; hold SHIFT for a multi-axis cursor</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.actionVertical_Cursor.setText(QCoreApplication.translate("SignalViewerWindow", u"Vertical", None))
#if QT_CONFIG(tooltip)
        self.actionVertical_Cursor.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Add a vertical cursor to the active axes;</p><p>press &amp; hold SHIFT for a multi-axis cursor</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.actionHorizontal_Cursor.setText(QCoreApplication.translate("SignalViewerWindow", u"Horizontal", None))
#if QT_CONFIG(tooltip)
        self.actionHorizontal_Cursor.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Add a horizontal cursor to the active axes", None))
#endif // QT_CONFIG(tooltip)
        self.actionRemove_Cursor.setText(QCoreApplication.translate("SignalViewerWindow", u"Remove Cursor...", None))
#if QT_CONFIG(tooltip)
        self.actionRemove_Cursor.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Removes the currently <span style=\" text-decoration: underline;\">selected</span> cursor.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.actionSVG.setText(QCoreApplication.translate("SignalViewerWindow", u"&SVG", None))
        self.actionTIFF.setText(QCoreApplication.translate("SignalViewerWindow", u"&TIFF", None))
        self.actionPNG.setText(QCoreApplication.translate("SignalViewerWindow", u"&PNG", None))
        self.actionDetect_Triggers.setText(QCoreApplication.translate("SignalViewerWindow", u"Detect Triggers", None))
        self.actionRefresh.setText(QCoreApplication.translate("SignalViewerWindow", u"Refresh", None))
#if QT_CONFIG(tooltip)
        self.actionRefresh.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Reload data", None))
#endif // QT_CONFIG(tooltip)
        self.actionData_to_workspace.setText(QCoreApplication.translate("SignalViewerWindow", u"Data to workspace", None))
        self.actionShow_Legends.setText(QCoreApplication.translate("SignalViewerWindow", u"Show Legends", None))
        self.actionIgnore_empty_spike_trains.setText(QCoreApplication.translate("SignalViewerWindow", u"Ignore empty spike trains", None))
        self.setCursorsShowValue.setText(QCoreApplication.translate("SignalViewerWindow", u"Cursor Label Shows Value", None))
        self.setCursorsLabelPrecisionAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Cursor Label Precision...", None))
        self.addVerticalCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Vertical", None))
        self.addHorizontalCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Horizontal", None))
        self.addMultiAxisVCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Vertical", None))
        self.addMultiAxisCCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Crosshair", None))
        self.addDynamicMultiAxisVCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Dynamic Vertical", None))
        self.addDynamicMultiAxisCCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Dynamic Crosshair", None))
        self.addCrosshairCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Crosshair", None))
        self.addDynamicVerticalCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Dynamic Vertical", None))
        self.addDynamicHorizontalCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Dynamic Horizontal", None))
        self.addDynamicCrosshairCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Dynamic Crosshair", None))
        self.editAnyCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Choose...", None))
        self.editCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Selected...", None))
        self.removeCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Remove A Cursor...", None))
        self.removeSelectedCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Remove Selected Cursor", None))
        self.removeAllCursorsAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Remove All Cursors", None))
        self.verticalCursorColorsAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Vertical  Cursor Colors", None))
        self.horizontalCursorColorsAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Horizontal Cursor Colors", None))
        self.crosshairCursorColorsAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Crosshair Cursor Colors", None))
        self.cursorHoverColorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Cursor Hover Color", None))
        self.epochsFromCursorsAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Create Epoch From Vertical Cursor...", None))
#if QT_CONFIG(tooltip)
        self.epochsFromCursorsAction.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Create Epoch From Vertical Cursor...", None))
#endif // QT_CONFIG(tooltip)
        self.epochFromSelectedCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Create Epoch From Selected Vertical Cursor", None))
#if QT_CONFIG(tooltip)
        self.epochFromSelectedCursorAction.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Create Epoch From Selected Vertical Cursor", None))
#endif // QT_CONFIG(tooltip)
        self.epochBetweenCursorsAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Create Epoch Between Two Vertical Cursors", None))
#if QT_CONFIG(tooltip)
        self.epochBetweenCursorsAction.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Create Epoch Between Two Vertical Cursors", None))
#endif // QT_CONFIG(tooltip)
        self.epochsInDataFromCursorsAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Add Epoch From Vertical Cursors", None))
#if QT_CONFIG(tooltip)
        self.epochsInDataFromCursorsAction.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Creates an Epoch from several vertical cursors.</p><p>Creates an Epoch with <span style=\" font-weight:700; font-style:italic;\">as many intervals as there are vertical cursors selected</span> in a subsequent dialog.</p><p>The Epoch is embedded in the data.</p><p>The Epoch will have <span style=\" text-decoration: underline;\">one interval for each selected vertical cursor</span>, defined by <span style=\" font-weight:700; font-style:italic;\">start</span> and <span style=\" font-weight:700; font-style:italic;\">duration</span> attributes, centered on the cursors' horizontal (<span style=\" font-weight:700; font-style:italic;\">x</span>) coordinate, with duration equal to the cursors' horizontal window (<span style=\" font-weight:700; font-style:italic;\">xwindow</span>).</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.epochInDataFromSelectedCursorAction.setText(QCoreApplication.translate("SignalViewerWindow", u"Add Epoch From Selected Vertical Cursor", None))
#if QT_CONFIG(tooltip)
        self.epochInDataFromSelectedCursorAction.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Creates an Epoch from a single vertical cursor.</p><p>The Epoch is embedded in the data.</p><p>The Epoch will have <span style=\" text-decoration: underline;\">one interval</span>, defined by <span style=\" font-weight:700; font-style:italic;\">start</span> and <span style=\" font-weight:700; font-style:italic;\">duration</span> attributes, centered on the cursors' horizontal (<span style=\" font-weight:700; font-style:italic;\">x</span>) coordinate, with duration equal to the cursors' horizontal window (<span style=\" font-weight:700; font-style:italic;\">xwindow</span>).</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.epochInDataBetweenCursors.setText(QCoreApplication.translate("SignalViewerWindow", u"Add Epoch Between Two Vertical Cursors", None))
#if QT_CONFIG(tooltip)
        self.epochInDataBetweenCursors.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Creates an epoch between two Vertical Cursors.</p><p>The Epoch is embedded in the data.</p><p>The Epochs will contain a single interval, between the two cursors <span style=\" font-weight:700; font-style:italic;\">x</span> coordinates.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.actionLink_X_axes.setText(QCoreApplication.translate("SignalViewerWindow", u"Link X axes", None))
#if QT_CONFIG(tooltip)
        self.actionLink_X_axes.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Link all X axes", None))
#endif // QT_CONFIG(tooltip)
        self.actionUnlink_X_Axes.setText(QCoreApplication.translate("SignalViewerWindow", u"Unlink X Axes", None))
#if QT_CONFIG(tooltip)
        self.actionUnlink_X_Axes.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Unlink all X axes", None))
#endif // QT_CONFIG(tooltip)
        self.actionShow_Cursor_Edit_Dialog_When_Created.setText(QCoreApplication.translate("SignalViewerWindow", u"Edit Cursor At Creation", None))
#if QT_CONFIG(tooltip)
        self.actionShow_Cursor_Edit_Dialog_When_Created.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Show Cursor Editing Dialog When Created", None))
#endif // QT_CONFIG(tooltip)
        self.actionVerticalCursorsFromEpochInCurrentAxis.setText(QCoreApplication.translate("SignalViewerWindow", u"In current axis...", None))
#if QT_CONFIG(tooltip)
        self.actionVerticalCursorsFromEpochInCurrentAxis.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Create Vertical Cursors from Epoch In current axis", None))
#endif // QT_CONFIG(tooltip)
        self.actionMultiAxisVerticalCursorsFromEpoch.setText(QCoreApplication.translate("SignalViewerWindow", u"Multi-axes...", None))
        self.actionShow_X_grid.setText(QCoreApplication.translate("SignalViewerWindow", u"Show X Grid on All Axes", None))
#if QT_CONFIG(statustip)
        self.actionShow_X_grid.setStatusTip(QCoreApplication.translate("SignalViewerWindow", u"Show X Grid on All Axes", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionShow_X_grid.setWhatsThis(QCoreApplication.translate("SignalViewerWindow", u"Show X Grid on All Axes", None))
#endif // QT_CONFIG(whatsthis)
        self.actionShow_Y_grid.setText(QCoreApplication.translate("SignalViewerWindow", u"Show Y Grid on All Axes", None))
#if QT_CONFIG(tooltip)
        self.actionShow_Y_grid.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Show Y Grid on All Axes", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionShow_Y_grid.setStatusTip(QCoreApplication.translate("SignalViewerWindow", u"Show Y Grid on All Axes", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.actionShow_Y_grid.setWhatsThis(QCoreApplication.translate("SignalViewerWindow", u"Show Y Grid on All Axes", None))
#endif // QT_CONFIG(whatsthis)
        self.actionViewMain_Toolbar.setText(QCoreApplication.translate("SignalViewerWindow", u"Main Toolbar", None))
        self.actionViewFrame_Navigator.setText(QCoreApplication.translate("SignalViewerWindow", u"Frame Navigator", None))
        self.actionViewSignal_Selectors.setText(QCoreApplication.translate("SignalViewerWindow", u"Signal Selectors", None))
        self.actionVertical_cursor_series.setText(QCoreApplication.translate("SignalViewerWindow", u"Vertical cursor series", None))
        self.actionLeft_Axis_Spacer.setText(QCoreApplication.translate("SignalViewerWindow", u"Left Axis Spacer", None))
        self.actionExportVerticalCursorData.setText(QCoreApplication.translate("SignalViewerWindow", u"Vertical", None))
        self.actionExportHorizontalCursorData.setText(QCoreApplication.translate("SignalViewerWindow", u"Horizontal", None))
        self.actionExportCrosshairCursorData.setText(QCoreApplication.translate("SignalViewerWindow", u"Crosshair", None))
        self.actionViewCursors_Toolbar.setText(QCoreApplication.translate("SignalViewerWindow", u"Cursors Toolbar", None))
        self.actionViewTriggers_Toolbar.setText(QCoreApplication.translate("SignalViewerWindow", u"Triggers Toolbar", None))
        self.actionLockToolbars.setText(QCoreApplication.translate("SignalViewerWindow", u"Lock Toolbars", None))
        self.actionRemoveTriggers.setText(QCoreApplication.translate("SignalViewerWindow", u"Remove Events and Triggers", None))
        self.actionRemoveAllEvents.setText(QCoreApplication.translate("SignalViewerWindow", u"Remove All Events", None))
        self.actionViewEpochs_Toolbar.setText(QCoreApplication.translate("SignalViewerWindow", u"Epochs Toolbar", None))
        self.actionRemove_All_Epochs.setText(QCoreApplication.translate("SignalViewerWindow", u"Remove All Epochs", None))
        self.actionEnable_Auto_Range.setText(QCoreApplication.translate("SignalViewerWindow", u"Enable Auto Range", None))
#if QT_CONFIG(tooltip)
        self.actionEnable_Auto_Range.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Enable Auto Range By Default (All axes)", None))
#endif // QT_CONFIG(tooltip)
        self.actionAutoScaleSelectedAxis.setText(QCoreApplication.translate("SignalViewerWindow", u"Auto Range (X,Y) for  Selected Axis", None))
#if QT_CONFIG(tooltip)
        self.actionAutoScaleSelectedAxis.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Auto Range (X,Y) for  Selected Axis", None))
#endif // QT_CONFIG(tooltip)
        self.actionRemove_All_Cursors.setText(QCoreApplication.translate("SignalViewerWindow", u"Remove Cursor...", None))
#if QT_CONFIG(tooltip)
        self.actionRemove_All_Cursors.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Remove <span style=\" text-decoration: underline;\">all</span> cursors.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.plotAnalogSignalsCheckBox.setText(QCoreApplication.translate("SignalViewerWindow", u"Analog:", None))
        self.plotIrregularSignalsCheckBox.setText(QCoreApplication.translate("SignalViewerWindow", u"Irregular", None))
        self.plotSpikeTrainsCheckBox.setText(QCoreApplication.translate("SignalViewerWindow", u"Spike trains", None))
        self.plotEventsCheckBox.setText(QCoreApplication.translate("SignalViewerWindow", u"Events", None))
        self.plotEpochsCheckBox.setText(QCoreApplication.translate("SignalViewerWindow", u"Epochs", None))
        self.menuFile.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Fi&le", None))
        self.menuExport.setTitle(QCoreApplication.translate("SignalViewerWindow", u"&Export", None))
        self.menuTools.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Analysis", None))
        self.menuTriggers.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Events and Triggers", None))
        self.menuSettings.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Settings", None))
        self.menuView.setTitle(QCoreApplication.translate("SignalViewerWindow", u"View", None))
        self.menuAxes.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Axes", None))
        self.cursorsMenu.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Cursors", None))
        self.addCursorsMenu.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Add Cursors", None))
        self.addMultiAxesCursorMenu.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Multi-axis", None))
        self.editCursorsMenu.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Edit Cursor", None))
        self.removeCursorsMenu.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Remove Cursors", None))
        self.cursorsColorsMenu.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Cursor Colors", None))
#if QT_CONFIG(tooltip)
        self.menuVerticalCursorsFromEpoch.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Create vertical cursors from Epoch", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.menuVerticalCursorsFromEpoch.setStatusTip(QCoreApplication.translate("SignalViewerWindow", u"Create vertical cursors from Epoch", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.menuVerticalCursorsFromEpoch.setWhatsThis(QCoreApplication.translate("SignalViewerWindow", u"Create vertical cursors from Epoch", None))
#endif // QT_CONFIG(whatsthis)
        self.menuVerticalCursorsFromEpoch.setTitle(QCoreApplication.translate("SignalViewerWindow", u"From Epoch", None))
        self.menuExport_Cursor_Data.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Export Cursor Data", None))
        self.epochsMenu.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Epochs", None))
#if QT_CONFIG(tooltip)
        self.makeEpochsMenu.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Creates Epochs and <span style=\" font-weight:700; font-style:italic;\">exports</span> them to the workspace. </p><p>Epochs are <span style=\" font-weight:700; font-style:italic;\">not added</span> to the data</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.makeEpochsMenu.setStatusTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Creates Epochs and <span style=\" font-weight:700; font-style:italic;\">exports</span> them to the workspace. </p><p>Epochs are <span style=\" font-weight:700; font-style:italic;\">not added</span> to the data</p></body></html>", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.makeEpochsMenu.setWhatsThis(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Creates Epochs and <span style=\" font-weight:700; font-style:italic;\">exports</span> them to the workspace. </p><p>Epochs are <span style=\" font-weight:700; font-style:italic;\">not added</span> to the data</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.makeEpochsMenu.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Create Epochs   ", None))
#if QT_CONFIG(tooltip)
        self.makeEpochsInDataMenu.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Creates Epochs and <span style=\" font-weight:700; font-style:italic;\">adds</span> them to the data. </p><p>Epochs are <span style=\" font-weight:700; font-style:italic;\">NOT</span> exported to the workspace</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.makeEpochsInDataMenu.setStatusTip(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Creates Epochs and <span style=\" font-weight:700; font-style:italic;\">adds</span> them to the data. </p><p>Epochs are <span style=\" font-weight:700; font-style:italic;\">NOT</span> exported to the workspace</p></body></html>", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.makeEpochsInDataMenu.setWhatsThis(QCoreApplication.translate("SignalViewerWindow", u"<html><head/><body><p>Creates Epochs and <span style=\" font-weight:700; font-style:italic;\">adds</span> them to the data. </p><p>Epochs are <span style=\" font-weight:700; font-style:italic;\">NOT</span> exported to the workspace</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.makeEpochsInDataMenu.setTitle(QCoreApplication.translate("SignalViewerWindow", u"Add Epochs To Data    ", None))
        self.cursorsDockWidget.setWindowTitle(QCoreApplication.translate("SignalViewerWindow", u"&Cursors", None))
        self.annotationsDockWidget.setWindowTitle(QCoreApplication.translate("SignalViewerWindow", u"Annotations", None))
        self.mainToolBar.setWindowTitle(QCoreApplication.translate("SignalViewerWindow", u"MainToolbar", None))
        self.cursorsToolBar.setWindowTitle(QCoreApplication.translate("SignalViewerWindow", u"Cursors", None))
#if QT_CONFIG(tooltip)
        self.cursorsToolBar.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Manage Cursors", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.cursorsToolBar.setStatusTip(QCoreApplication.translate("SignalViewerWindow", u"Manage Cursors", None))
#endif // QT_CONFIG(statustip)
        self.triggersToolBar.setWindowTitle(QCoreApplication.translate("SignalViewerWindow", u"Triggers", None))
#if QT_CONFIG(tooltip)
        self.triggersToolBar.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Events and Triggers", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.triggersToolBar.setStatusTip(QCoreApplication.translate("SignalViewerWindow", u"Add or remove Triggers and Events", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.triggersToolBar.setWhatsThis(QCoreApplication.translate("SignalViewerWindow", u"Add or remove Triggers and Events", None))
#endif // QT_CONFIG(whatsthis)
        self.epochsToolBar.setWindowTitle(QCoreApplication.translate("SignalViewerWindow", u"Epochs", None))
#if QT_CONFIG(tooltip)
        self.epochsToolBar.setToolTip(QCoreApplication.translate("SignalViewerWindow", u"Manage Epochs", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.epochsToolBar.setStatusTip(QCoreApplication.translate("SignalViewerWindow", u"Manage Epochs", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.epochsToolBar.setWhatsThis(QCoreApplication.translate("SignalViewerWindow", u"Manage Epochs", None))
#endif // QT_CONFIG(whatsthis)
    # retranslateUi

