#!/bin/sh
# SPDX-FileCopyrightText: 2024 Cezar M. Tigaret <cezar.tigaret@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LGPL-2.1-or-later


original=`realpath $0`
location=`dirname $original`

ipython --matplotlib --gui=qt5 -i $location/nrnipython.ipy -- $*
# if [ $# == "0" ]; then
#     ipython --matplotlib --gui=qt5 -i $location/nrn-ipython.ipy
# #     juoyter qtconsole --matplotlib --gui=qt5 -i $location/nrn-ipython.ipy
#     
# else
#     ipython --matplotlib --gui=qt5 -i $location/nrn-ipython.ipy -- $*
#     
# fi
