#!/bin/sh
original=`realpath $0`
location=`dirname $original`

ipython --matplotlib --gui=qt5 -i $location/nrnipython.ipy -- $*
# if [ $# == "0" ]; then
#     ipython --matplotlib --gui=qt5 -i $location/nrn-ipython.ipy
# #     juoyter qtconsole --matplotlib --gui=qt5 -i $location/nrn-ipython.ipy
#     
# else
#     ipython --matplotlib --gui=qt5 -i $location/nrn-ipython.ipy -- $*
#     
# fi
