# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2024 Cezar M. Tigaret <cezar.tigaret@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LGPL-2.1-or-later

r"""Base ancestor of Scipyen's data objects: AnalysisUnit, ScanData
"""
import functools, typing, dataclasses, pathlib, types
import collections
from collections import deque
from datetime import datetime, date, time, timedelta
from dataclasses import (dataclass, field, MISSING, KW_ONLY, InitVar)
import numpy as np
import quantities as pq
import neo
import h5py
from core.vigra_patches import vigra
import pandas as pd
from traitlets.utils.importstring import import_item
from core import scipyen_quantities as cq
# from core.triggerprotocols import TriggerProtocol
from core.scipyen_quantities import unitsConvertible

# from core.datatypes import * # clashes with datetime class imported from datetime module !!!
from core.typeenum import TypeEnum
from core.scipyendataclasses import (Episode, Schedule, ProcedureType, AdministrationRoute,
                            Procedure, BioSourceType, TaxonDescriptor, Taxon,
                            BiologicalSource, CellCompartment, CellCompartmentType,
                            Organism, Biometrics, ScipyenDataclass,
                            FileOriginDescriptor
                            )

from iolib.navigation.filesystems import getFileCreationDateTime

@dataclass
class BaseScipyenData(ScipyenDataclass):
    r"""Encapsulates 'metadata' associated with recorded data or analysis results"""
    # NOTE: 2024-11-16 10:07:21
    # The fields below, from 'name' to 'rec_datetime' are meant to align this
    # data model to the one used in NeuralEnsemble's neo library.
    # In addition, I introduce an "analysis_datetime" field to ease up tracking
    # analysis times, and a "triggers" field (which may not be generally useful,
    # see NOTE below)
    # name:str = ""
    # description:str = ""
    # file_origin: typing.Union[
    #     str, pathlib.Path
    #     ] = dataclasses.field(default="")


    # NOTE: 2026-03-05 23:34:21
    # file_origin refers to the file(s) origin of the object that associates
    # this structure:
    # • If the associating object is primary data, file_origin refers to the
    # data files generated typically by the acquisition software (or by Scipyen
    # itself for exasmple in the case of generated signals, etc)
    #
    # If the associating object is an analysis result, this refers to the
    # primary data files (again, generated by the acquisition software or by
    # Scipyen) that contain the data used to obtain the analysis result
    #
    # So in either case, this NEVER refers to the file that STORES the metadata
    # unless the metadata is part of a python object as above.
    file_origin: FileOriginDescriptor = FileOriginDescriptor()

    # creation time stamp, for the file_origin
    file_datetime: typing.Optional[datetime] = dataclasses.field(
        # default_factory = datetime.now
        default = None
        )

    # NOTE: 2026-03-05 23:42:26
    # rec_datetime - refers to the time stamp of data recording
    # relevant only when the metadata is associated with recorded data, and is
    # usually supplied by the acquisition software (e.g. Clampex includes this in
    # ABF files)
    rec_datetime: typing.Optional[datetime] = dataclasses.field(
        # default_factory = datetime.now
        default = None
        )

    # when was data analysed
    # relevant whehn metadata is associated with a results object.
    analysis_datetime: typing.Optional[datetime] = dataclasses.field(
        # default_factory = datetime.now
        default = None
        )

    # NOTE: 2024-11-16 10:10:16 Revisit this:
    # 'triggers' does not seem useful for this generic data type; it might be better
    # introduced with SOME descendant classes, or included in the Procedure model
    # (with the caveat that it would be too deeply nested in the final object)
    # triggers:typing.Union[TriggerProtocol, list] = dataclasses.field(default_factory=TriggerProtocol)

    # biological source including organism, organ, tissue, cell, ID,
    source: BiologicalSource = dataclasses.field(
        default_factory=BiologicalSource
        )
    # includes treatment, with dosage route, and schedule; does NOT include triggers
    # as these are specific to ephys/imaging protocols.
    procedure: Procedure = dataclasses.field(default_factory=Procedure)

    def __repr__(self):
        indent = lambda x: x.replace("\n", "\n\t")
        repr_attr = lambda x: f": {type(x).__name__} → '{x}'" if isinstance(x, str) else f": {type(x).__name__} → {indent(x.__repr__())}" if dataclasses.is_dataclass(type(x)) else f": {type(x).__name__} → {x}" # noqa
        ret = [f"{self.__class__.__name__}:"] + sorted([f"\t{a}{repr_attr(getattr(self, a))}" for a in self.__match_args__])
        return "\n".join(ret)

    def __post_init__(self, *args, **kwargs):
        if self.file_datetime is None:
            if isinstance(self.file_origin, typing.Sequence) and all(isinstance(f, (str, pathlib.Path)) for f in self.file_origin):
                self.file_datetime = list(map(lambda f: getFileCreationDateTime(f), self.file_origin))

            elif isinstance(self.file_origin, (str, pathlib.Path)):
                self._file_datetime = getFileCreationDateTime(self.file_origin)


class BaseResult(types.SimpleNamespace):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


